### ISSUE TITLE
(Feat) NSFW/SFW filtering options?

### ISSUE THREAD

**Issue by gabegears** [Minds/minds#10]
I would like to browse from work however, there is no indication (in settings or timeline) that I can find that allows you to decide if posts marked as mature or not will appear.

**Comment by markharding** [comment]
Posts should be marked as E if explicit. You can click on them to see.

**Comment by gabegears** [comment]
I understand I can mark my own posts, however if I browse https://www.minds.com/discovery/suggested/images there is no option to allow explicit content or not, it seems to appear anyways.

**Comment by markharding** [comment]
Please send support requests to https://www.minds.com/groups/profile/100000000000000681/activity.
