### ISSUE TITLE
(bug): localhost:5672 missing in dev environment

### ISSUE THREAD

**Issue by gem2578** [Minds/minds#100]
The `docker-compose up installer` works but returns:
`cli.php: [EXCEPTION:ErrorException] stream_socket_client(): unable to connect to tcp://localhost:5672 (Address not available)`

When making a new post:
`stream_socket_client(): unable to connect to tcp://localhost:5672 (Address not available)`
<img width="748" alt="error" src="https://user-images.githubusercontent.com/8502138/39496710-924bb52a-4d97-11e8-9920-5a3efb8ec604.png">

**Comment by markharding** [comment]
It would be great if a member of the community could take this bug. We need to make sure that the RabbitMQ Client (engine/Core/Queue/RabbitMQ/Client) can support $CONFIG variables for the host.

**Comment by gem2578** [comment]
@markharding It looks like the QueueProvider (engine/Core/Queue/QueueProvider) support $CONFIG variables

https://github.com/Minds/engine/blob/b91624a85aaf8984a496e8ba971ef3467e1b5f65/Core/Queue/QueueProvider.php#L31

**Comment by gem2578** [comment]
@markharding the two pull requests will fix the error. However there is still the duplicated call to the AMQPConnection constructor
