### ISSUE TITLE
[feat_req] Please introduce a dark theme option, perhaps even as default!

### ISSUE THREAD

**Issue by progenyx** [Minds/minds#105]
It's getting harder and harder these days to spend any considerable amount of time on the platform without constantly tuning out in order to save ones vision. And once one switches to another platform that offers this very crucial feature, special circumstances are generally required to remind one to tune back in. In my opinion, this makes is almost impossible to run a successful platform in the long run.

Now, there are of course solutions (more like workarounds, really) out there that offer this feature -- however, these only work with the two main browsers (i.e. Firefox and Chromium), and more so, these so called solutions are usually just general settings designed to work with most web sites and as such they're not optimized for individual ones.

That's where, I think, your responsibility comes in.

As the majority of use cases involve using the platform indoors, in my view, it would make even more sense to use the dark mode by default and allow a light mode option for extremely sunny conditions when one can't find or create shade. Making it the default, of course, would require some feedback from the community, but you can still come half way with it.

**Comment by gem2578** [comment]
A good place to start looking at creating new themes would be here:
https://github.com/Minds/front/tree/master/src/stylesheets

**Comment by markharding** [comment]
Please submit feature requests to https://www.minds.com/groups/profile/100000000000000681. Thanks

**Comment by Serkan-devel** [comment]
#94 for context
