### ISSUE TITLE
Could not connect to Cassandra after docker install

### ISSUE THREAD

**Issue by liruqi** [Minds/minds#106]
I installed minds on Azure Ubuntu 16.04 VM:
# cat /etc/issue
Ubuntu 16.04.4 LTS \n \l

After install with docker, I cannot create new account, and front could not connect to Cassandra. 

How can I change this "[0]" to localhost?

docker logs:

php-fpm_1        | [08-May-2018 01:24:22] WARNING: [pool www] child 173 said into stderr: "NOTICE: PHP message: Error connecting to cassandra: Thrift\Exception\TException: TSocket: Could not connect to cassandra:9160 (php_network_getaddresses: getaddrinfo failed: Name does not resolve [0])"
php-fpm_1        | 172.18.0.3 -  08/May/2018:01:24:22 +0000 "GET /index.php" 200
nginx_1          | 2018/05/08 01:24:22 [error] 7#7: *420 FastCGI sent in stderr: "PHP message: Error connecting to cassandra: Thrift\Exception\TException: TSocket: Could not connect to cassandra:9160 (php_network_getaddresses: getaddrinfo failed: Name does not resolve [0])
nginx_1          | PHP message: Error connecting to cassandra: Thrift\Exception\TException: TSocket: Could not connect to cassandra:9160 (php_network_getaddresses: getaddrinfo failed: Name does not resolve [0])
nginx_1          | PHP message: Error connecting to cassandra: Thrift\Exception\TException: TSocket: Could not connect to cassandra:9160 (php_network_getaddresses: getaddrinfo failed: Name does not resolve [0])
nginx_1          | PHP message: Error connecting to cassandra: Thrift\Exception\TException: TSocket: Could not connect to cassandra:9160 (php_network_getaddresses: getaddrinfo failed: Name does not resolve [0])" while reading upstream, client: 125.33.50.79, server: _, request: "GET /nullassets/videos/what-1/what-1.mp4 HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "52.175.9.80:8080", referrer: "http://52.175.9.80:8080/"

Any suggestions / ideas? Thanks in advance.

**Comment by liruqi** [comment]
Fixed this by editting engine/settings.php

Another issue: Could not connect to 127.0.0.1:9160

nginx_1          | 2018/05/08 06:53:32 [error] 7#7: *21 FastCGI sent in stderr: "PHP message: Error connecting to 127.0.0.1: Thrift\Exception\TException: TSocket: Could not connect to 127.0.0.1:9160 (Connection refused [111])
nginx_1          | PHP message: Error connecting to 127.0.0.1: Thrift\Exception\TException: TSocket: Could not connect to 127.0.0.1:9160 (Connection refused [111])", client: 47.74.252.148, server: _, request: "GET / HTTP/1.1", host: "52.175.9.80:8080", referrer: "http://52.175.9.80:8080/"
nginx_1          | 2018/05/08 06:53:34 [error] 7#7: *21 FastCGI sent in stderr: "PHP message: Error connecting to 127.0.0.1: Thrift\Exception\TException: TSocket: Could not connect to 127.0.0.1:9160 (Connection refused [111])
nginx_1          | PHP message: Error connecting to 127.0.0.1: Thrift\Exception\TException: TSocket: Could not connect to 127.0.0.1:9160 (Connection refused [111])
nginx_1          | PHP message: Error connecting to 127.0.0.1: Thrift\Exception\TException: TSocket: Could not connect to 127.0.0.1:9160 (Connection refused [111])
nginx_1          | PHP message: Error connecting to 127.0.0.1: Thrift\Exception\TException: TSocket: Could not connect to 127.0.0.1:9160 (Connection refused [111])", client: 47.74.252.148, server: _, request: "GET /tile.component.scss HTTP/1.1", host: "52.175.9.80:8080", referrer: "http://52.175.9.80:8080/"
nginx_1          | 2018/05/08 06:53:44 [error] 7#7: *21 FastCGI sent in stderr: "PHP message: Error connecting to 127.0.0.1: Thrift\Exception\TException: TSocket: Could not connect to 127.0.0.1:9160 (Connection refused [111])

**Comment by liruqi** [comment]
2ed issue fixed by # out the following lines

    mem_limit: 4048MB
    volumes:
      - "./cassandra:/var/lib/cassandra:cached"
      - "./logs:/var/log"

Ref: https://github.com/Minds/minds/issues/99

**Comment by markharding** [comment]
Can you try updating the engine folder? We no longer use thrift. Closing as we no longer use thrift. See #93 for more info.
