### ISSUE TITLE
Feature Request - Privacy select on posts

### ISSUE THREAD

**Issue by ayumihamsaki** [Minds/minds#107]
Hello,

Is it possible to create a feature where we can create a post and then select it with one of the following features like Facebook does, for example:

- Public
- Friends
- Only Me

No offense but I don't like the idea of writing a post and letting the whole world be able to view it. Sometimes I want to write posts friends 2 friends (without having to create a private group in minds to do that).

**Comment by markharding** [comment]
Please visit https://www.minds.com/groups/profile/100000000000000681 for feature requests. Thanks.

**Comment by Serkan-devel** [comment]
@ayumihamsaki #94 might be relevant to discussion

**Comment by ayumihamsaki** [comment]
Thanks Serkan-devel for the tip, but I have left minds due to markharding comments in github telling many people to file technical and feature request issues outside github!
