### ISSUE TITLE
docker-compose.yml

### ISSUE THREAD

**Issue by MindsGaming** [Minds/minds#110]
Running any docker command produces error
Example output on Ubuntu 

docker-compose up -d nginx
![screenshot_2018-06-06_14-36-21](https://user-images.githubusercontent.com/19932832/41058183-216ced26-6997-11e8-8b2a-a38fd6c4d5b4.png)

ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by markharding** [comment]
Can you check you have the latest version? https://github.com/Minds/minds/blob/master/docker-compose.yml#L2 is `2.2` not `2`

**Comment by MindsGaming** [comment]
Seems that it says "2.2" in the .yml file 
![screenshot_2018-06-06_14-49-49](https://user-images.githubusercontent.com/19932832/41058874-ef43a2c0-6998-11e8-97ff-cedd2c3e8df5.png)

**Comment by markharding** [comment]
Closing this as it doesn't appear to be a Minds issue.
