### ISSUE TITLE
Error on docker-compose up -d nginx

### ISSUE THREAD

**Issue by rakshitmidha** [Minds/minds#115]
➜  minds git:(master) ✗ docker-compose up -d nginx
Pulling cassandra (cassandra:3.11.1)...
ERROR: Get https://registry-1.docker.io/v2/library/cassandra/manifests/3.11.1: unauthorized: incorrect username or password

**Comment by markharding** [comment]
dd4fc9e82e60d1a7ab862c568643a4d8ba80a6f8

**Comment by Serkan-devel** [comment]
@markharding just as said, better would be to leave this issue open for feedback until it's confident that it works for others
