### ISSUE TITLE
language file

### ISSUE THREAD

**Issue by singuyen** [Minds/minds#116]
Hi guys,

First, do minds support multi languages?
I found the EN here. https://github.com/Minds/minds/tree/master/languages, doesn't seems it's being expanded to multi languages?

Thanks
S

**Comment by Serkan-devel** [comment]
They are waiting for the Angular framework for multilanguage support

**Comment by markharding** [comment]
You can contribute to the language translations here
https://poeditor.com/projects/view?id=145431
