### ISSUE TITLE
Error on Build

### ISSUE THREAD

**Issue by datgb** [Minds/minds#118]
Issue with build. First error was Error: No container found for cassandra_1

Got past that and now this.

```
sudo docker-compose up cassandra
Starting minds_cassandra_1 ... done
Attaching to minds_casssandra_1
cassandra_1       | chown: cannot access
'var/log/cassandra': No such File or directory
minds_cassandra_1 exited with code 1
```

**Comment by PlanetBooster-DEV** [comment]
Has anyone received any help or a solution?

**Comment by paolodina** [comment]
I'm stuck here too.

Related: https://github.com/Minds/minds/issues/99

It's not clear to me how to fix though.
