### ISSUE TITLE
[Feature Request] Filter shown languages

### ISSUE THREAD

**Issue by Strit** [Minds/minds#120]
I know this is a long shot and probably difficult to implement.

But since the Vietnamese migrated to Minds, 90% of my boost/top feeds are in vietnamese. 
I can't read vietnamese and I have no intention of pressing the "translate post" button, just to see what's going on.

I would much rather be able to just not see these posts all together.

So I suggest implementing some form of language recognition (must already be present, since you can translate posts), and make it possible from the User Settings to define what languages you would like to see posts in.

I would for example be capable of reading English and Danish posts, so would check the boxes for these two.
When I then browse the feeds, all posts that does not match these, will not get shown. 

Thanks for reading and maybe considering.
It's one of the big issues I have with Minds these days.

**Comment by ottman** [comment]
This is coming!

**Comment by Strit** [comment]
Awesome. Can't wait!
