### ISSUE TITLE
Hosting Minds

### ISSUE THREAD

**Issue by ghost** [Minds/minds#123]
This is probably quite far-fetched but it would be a legendary step towards freedom if users had more hosting options such as:

1. self-cloud
2. self-hosted <- This could even be sold as a software product
3. the status quo SaaS

This would require making platform independent builds and ideally requiring no additional setup and configuration from users, like any other portable application, so that it's convenient for users with any skill level to participate.

The challenge will be to stop thinking in terms of a monolithic Minds database and more towards users keeping their own data.

This requires a good measure of architectural work.

**Comment by ashtonhogan** [comment]
If we go ahead with this, here's a reminder to list it [here](https://github.com/Kickball/awesome-selfhosted).

**Comment by Serkan-devel** [comment]
The was a hosting option before, and some selected users still have it https://mindsgaming.minds.com/
