### ISSUE TITLE
Keyspace 'minds' does not exist

### ISSUE THREAD

**Issue by pavank1933** [Minds/minds#127]
When i try to enter the following command to build
$ docker-compose up front-build

Facing the below issue:

Fatal error: Uncaught Cassandra\Exception\RuntimeException: Keyspace 'minds' does not exist in /var/www/Minds/engine/Core/Data/Cassandra/Client.php:32 Stack trace: #0 /var/www/Minds/engine/Core/Data/Cassandra/Client.php(32): Cassandra\DefaultCluster->connect('minds') #1 /var/www/Minds/engine/Core/Data/DataProvider.php(37): Minds\Core\Data\Cassandra\Client->__construct() #2 [internal function]: Minds\Core\Data\DataProvider->Minds\Core\Data\{closure}(Object(Minds\Core\Di\Di)) #3 /var/www/Minds/engine/Core/Di/Di.php(25): call_user_func(Object(Closure), Object(Minds\Core\Di\Di)) #4 /var/www/Minds/engine/Core/Data/Call.php(47): Minds\Core\Di\Di->get('Database\\Cassan...') #5 /var/www/Minds/engine/Core/Data/Sessions.php(27): Minds\Core\Data\Call->__construct('session') #6 /var/www/Minds/engine/Core/Session.php(24): Minds\Core\Data\Sessions->__construct() #7 /var/www/Minds/engine/Core/Minds.php(86): Minds\Core\Session->__construct() #8 /var/www/Minds/engine/start.php(23): Minds\Core\Minds->start() #9 /var/www/Minds/engine/index. in /var/www/Minds/engine/Core/Data/Cassandra/Client.php on line 32

Please help me out

**Comment by pavank1933** [comment]
@ottman Any help on this please.  I am very much novice to this.

**Comment by huangyingw** [comment]
I am debugging this issue for myself for sometimes.
This error is from this line:

`
$this->session = $this->cluster->connect($options['keyspace']);
in engine/Core/Data/Cassandra/Client.php.
`

When attaching to the cassandra containder, and run following command:

`
cqlsh> DESCRIBE KEYSPACES ;
system_traces  system_schema  system_auth  system  system_distributed
`

There is no keyspace called 'minds'.
I am searching through the code, hoping to see how to create the 'minds' keyspace.
Once found, this issue should be fixed.

**Comment by markharding** [comment]
dd4fc9e82e60d1a7ab862c568643a4d8ba80a6f8 should resolve. Please re-open with further spec/details if you are still having issues. Thanks.

**Comment by Serkan-devel** [comment]
Umm, @pavank1933 , do you even see an option to re-open this issue? You can't

**Comment by dsun29** [comment]
@markharding I have the same issue after fresh installation this morning. The minds keyspace is not just there.

> [dsun@localhost ~]$ docker exec -it minds_cassandra_1 /bin/bash
> root@84df9a6fa57c:/# cqlsh
> Connected to Test Cluster at 127.0.0.1:9042.
> [cqlsh 5.0.1 | Cassandra 3.11.1 | CQL spec 3.4.4 | Native protocol v4]
> Use HELP for help.
> cqlsh> describe keyspaces;
> 
> system_traces  system_schema  system_auth  system  system_distributed
> 
> cqlsh> 
>
