### ISSUE TITLE
Like in the comment but when loading again do not save value.

### ISSUE THREAD

**Issue by phanhien9218** [Minds/minds#128]
I have successfully set up minds locally, and are developing features, but when I like comments on status when loaded back do not save the value. In the same situation, status is good.Thanks for answering.

**Comment by evanlinwood** [comment]
Hi @phanhien9218 - I'm wondering did you install from docker images? Did you have many problems getting through the install process? Thanks!

**Comment by PlanetBooster-DEV** [comment]
>           I have successfully set up minds locally, and are developing features, but when I like comments on status when loaded back do not save the value. In the same situation, status is good.Thanks for answering.

How did you install.  Could you provide install details.  Much appreciated.
