### ISSUE TITLE
Can't clone repository

### ISSUE THREAD

**Issue by theunknownartisthour** [Minds/minds#13]
The submodules front and engine are easy to fix, but the sockets submodule doesn't seem to exist?

in .gitmodules I'd assume
```
[submodule "engine"]
	path = engine
	url = https://github.com/minds/engine.git
[submodule "front"]
	path = front
	url = https://github.com/minds/front.git
[submodule "sockets"]
	path = sockets
	url = https://github.com/minds/sockets.git
```

That's my best guess.

**Comment by LokiFawkes** [comment]
Same, no Sockets module found.

**Comment by SirCoolness** [comment]
i think the sockets module is deprecated, but dont take my word
