### ISSUE TITLE
on running, docker-compose up installer  Getting EXCEPTION:RegistrationException 

### ISSUE THREAD

**Issue by codevector** [Minds/minds#132]
cli.php: [EXCEPTION:RegistrationException] Password must have more than 8 characters. Including uppercase, numbers, special characters (ie. !,#,@), and cannot have spaces.

**Comment by markharding** [comment]
Can you confirm that your engine folder is up to date? Also, please send
over details about your environment (OS, Docker versions, etc).

**Comment by codevector** [comment]
Hi
Sorry for late reply.
Before using minds, i have downloaded the latest version of engine folder.
My env details as follows
1) OS -- Linux Mint
2) docker -- Docker version 18.06.0-ce, build 0ffa825
