### ISSUE TITLE
docker-compose up install fails due to missing dependencies

### ISSUE THREAD

**Issue by hopeseekr** [Minds/minds#133]
## The Problem

OS: Arch Linux x64, 4.18.12-arch1
Docker version: 18.06.1-ce
Docker-Compose version: 1.2..0

Running the command `docker-compose up installer` fails due to missing dependencies:

![image](https://user-images.githubusercontent.com/1125541/47825209-99a15c80-dd3e-11e8-8cf1-f3135419df18.png)

## The Solution

First, run `sh` inside the image so that it can be troubleshooted:

```
docker run -it --entrypoint=sh -v $PWD/engine:/var/www/Minds/engine -v $PWD/front:/var/www/Minds/front -v $PWD/.dev:/.dev minds_installer
```

Second, run the commands one by one.

Third, add the appropriate commands for installing the missing dependencies using the `apk` command for the Alpine Linux container into the relevant `Dockerfile`.

**Comment by hopeseekr** [comment]
Oops! I found out after I created the Issue that the relevant files were in a subrepository. I'm not sure whether I should create a dupe ticket over at Minds/engine or just leave it here? I'll leave it up to you guys.

**Comment by dsun29** [comment]
@hopeseekr it seems I have experienced every issue you have experienced.
