### ISSUE TITLE
http://localhost:8080/ delivers a 403 Forbidden

### ISSUE THREAD

**Issue by hopeseekr** [Minds/minds#134]
## The Problem
Upon following the directions to the letter, when I go to http://localhost:8080/ I get a 403: Forbidden nginx error screen:

![image](https://user-images.githubusercontent.com/1125541/47827079-b7c08a00-dd49-11e8-8623-cce11ea7566e.png)

While it is non-trivial to figure it out, the problem is that Language Auto-Detection is not performed, seemingly anywhere, and thus the user is not redirected to the appropriate `dist/{language}` folder (`dist/en` by default).

## The Solution
I implemented the industry-accepted way to redirect to the user's `Accept-Language` header setting directly via nginx. 

Assuming French and English are the only two supported languages:

- If the user has the header, `fr, en`, it will show the French page.
- If the user has the header `es, en`, it will show the English page.
- If the user does not set a header (some search engines, curl, etc.), it will show the English page.

It's not as detailed as the `AcceptLanguages` nginx extension, but it also doesn't require you to custom-compile nginx and ensure it's continually uptodate, either. I've used this setting in my own sites and never had a problem.

This only applies to the `/` route. It is assumed that any other route will be in the desired language. To implement a more detailed language check, it would require much more advanced JS sniffing that is beyond the scope of this issue.

**Comment by markharding** [comment]
It should be hitting engine/index.php, not front/dist/index.php -> https://github.com/Minds/minds/blob/master/containers/nginx/minds.conf#L94

Can you confirm what your HEAD commit is?

**Comment by dsun29** [comment]
I got the same 403 error after a fresh install.

**Comment by markharding** [comment]
Could you please run `ls front/dist` and let me know the output? Did you
get any errors when running `docker-compose up front-build`?

**Comment by dsun29** [comment]
ls front/dist
> 3rdpartylicenses.txt  inline.318b50c57b4eba3d437b.bundle.js  ionicons.dd4781d1acc57ba4c480.ttf                 MaterialIcons-Regular.a37b0c01c0baf1888ca8.ttf  styles.4119be19b325b0a94fa2.bundle.css
> assets                ionicons.19e65b89cee273a249fb.eot      main.a79806ae7d0e5c09c04a.bundle.js               MaterialIcons-Regular.e79bfd88537def476913.eot  Symbola-Emoji.4500f42b11d9227225b6.woff
> en                    ionicons.28df6ee7b407fd8a14b4.svg      MaterialIcons-Regular.012cf6a10129e2275d79.woff   polyfills.2e3218140a7b9abe27b2.bundle.js        Symbola-Emoji.464d9809358f3fb98204.ttf
> index.php             ionicons.2c159d0d05473040b53e.woff     MaterialIcons-Regular.570eb83859dc23dd0eec.woff2  scripts.9e3b02d977ecf3bf845e.bundle.js          Symbola-Emoji.dd47974749d03ada49c1.eot

The file en/index.php exists in the dist folder. but I don't know why the owner of the dist folder is root:root because I didn't not use sudo at all in my last installation

I did get an error iwhen running `docker-compose up front-build` saying "npm is not found" (or a few "xx module is missing"). As a result, I had to go to ./front folder and run "npm install". It no longer gives error after manual npm install.

**Comment by dsun29** [comment]
@markharding as I answered your last question I found the folder dist belongs to root:root. I tried chmod -R 777 dist the "file not found" error is gone.

**Comment by markharding** [comment]
I'm not sure why you would be having issues with `docker-compose up front-build` and this is exactly the same container our CI uses, but if you want to run the build out of docker then you will need to run `npm run build-dev` (this could lead to permission issues though).

**Comment by MindsGaming** [comment]
This issue should be solved?
