### ISSUE TITLE
Failed to clone https://0544aedfc74db62dcd39301588cd672b2b91e060@github.com/minds/mw3.git, git was not found

### ISSUE THREAD

**Issue by dsun29** [Minds/minds#136]
Hi guys,

I am trying to install MINDS to my local CentOS7 box. I get error as shown below when running "sudo docker-compose up installer". The git command IS in both my PATH and root's PATH as I can run successfully **git clone ...** and **sudo git clone**. So what do you think the cause can be?

My another question is regarding "Do not run Composer as root/super user!". Does this mean I should not run "docker-compose up installer" as root ? Anyways, the output is the same whether I run it as root or not.

> INSTALLING MINDS
> installer_1      | Installer verified
> installer_1      | All settings correct for using Composer
> installer_1      | Downloading...
> installer_1      | 
> installer_1      | Composer (version 1.7.3) successfully installed to: /var/www/Minds/engine/composer.phar
> installer_1      | Use it: php composer.phar
> installer_1      | 
> installer_1      | Do not run Composer as root/super user! See https://getcomposer.org/root for details
> installer_1      | Loading composer repositories with package information
> installer_1      | Installing dependencies (including require-dev) from lock file
> installer_1      | Package operations: 125 installs, 0 updates, 0 removals
> installer_1      |   - Installing minds/mw3 (dev-master 2f97f01): Cloning 2f97f01f0a
> installer_1      | 
> installer_1      |                                                                                                                                                                   
> installer_1      |   [RuntimeException]                                                                                                                                              
> installer_1      |   Failed to clone https://0544aedfc74db62dcd39301588cd672b2b91e060@github.com/minds/mw3.git, git was not found, check that it is installed and in your PATH env.  
> installer_1      |                                                                                                                                                                   
> installer_1      |   sh: git: not found

**Comment by markharding** [comment]
Closing this as it's a duplicate to #133. Not sure why we aren't experiencing this on our own builds, perhaps because the /vendor folder already exists. 

Could you try running

```
cd engine && composer install && cd ..
rm engine/settings.php
docker-compose up install
```

**Comment by markharding** [comment]
^^ you will need to https://getcomposer.org/ locally for this
