### ISSUE TITLE
Question: what is elasticsearch for

### ISSUE THREAD

**Issue by dsun29** [Minds/minds#137]
In the settings.json there are a couple entries for elasticsearch. However, ES is not installed for the development environment. So, what is ES for?

**Comment by Serkan-devel** [comment]
I think the purpose of elasticsearch is already in the name

**Comment by dsun29** [comment]
@Serkan-devel I know what ES as an application is. But how is it being used by Minds and why do not install it for development?

**Comment by dsun29** [comment]
I am closing this one and hope someone can help me with #140
