### ISSUE TITLE
photos not showing up feeds

### ISSUE THREAD

**Issue by dsun29** [Minds/minds#139]
after successful install I tried to post a feed with photo and texts. However, the photo I selected is not showing up in the feed. Instead, a yellow bulb(Mind's logo) is showing up. And it shows black rectangle if I click the yellow bulb. The texts are there. 

Are photos stored in Cassandra, MongoDB, or some file system? I cannot find particular errors in the docker logs for image upload/storage.

**Comment by dsun29** [comment]
This error is a result of wrong url. Eg, 

> http://localhost:8080/en/api/v1/media/thumbnails/906315340034609160/large

should be

> http://localhost:8080/api/v1/media/thumbnails/906315340034609160/large

**Comment by Serkan-devel** [comment]
@dsun29 I think it should be `xlarge` instead of `large` at the end of the URL

**Comment by dsun29** [comment]
@Serkan-devel it is large for sure. I got the link first from Chrome the browser, then from line 34 of engine/Controllers/api/v1/media.php

**Comment by dsun29** [comment]
this error can be fixed by removing ""/en" from cdn_url.

Another option is to manipulate the values of Entity->paywall field. I am so new to it that I have not figured out what paywall is for.
