### ISSUE TITLE
Possible Javascript Injection

### ISSUE THREAD

**Issue by theunknownartisthour** [Minds/minds#14]
I heard someone mention posts which instead of leading to an article instead open up the prompt to transfer points.

Found one such link, I'll be digging into it more tommorow, for now I'm leaving it here if someone would like to investigate: 
https://www.minds.com/blog/view/639940517336985602

**Comment by ottman** [comment]
I've experienced this a couple times. Thanks

**Comment by theunknownartisthour** [comment]
This appears to be Chrome related :+1: here's another link that's been found
https://www.minds.com/newsfeed/642119343630458890

Didn't think to switch browsers, but now that i have, what I've found is both these blog posts have google ads on them. I'm not sure that you've setup Minds.com to run ads, but these appear very out of place eaither way. The posters might be adding their own adsense embed links or scripts which chrome appears to be having a fit because of a security issue. The ads are insecure, the embedded javascript then crashes and then angular has a fit and renders is how this seems to be going.

**Comment by markharding** [comment]
Hi there,

This is down to ad blockers / bad connection from the ad provider.

**Comment by theunknownartisthour** [comment]
John caught onto that, I often forget I have an adblocker on by default in chrome. Unless things have changed between then and today I'm noticing those links are working again. The only difference seems to be the ads being inserted in.
