### ISSUE TITLE
[Feature Request] 2FA Authenticator Apps

### ISSUE THREAD

**Issue by trymeouteh** [Minds/minds#143]
Currently Minds uses a phone number for 2FA and I am glad Minds has some sort of 2FA. But I would like to use an Authenticator app like Authy instead of a phone number. That way people can secure their accounts without their phone number and it will be cheaper for minds.com since sending a verify sms when setting up 2FA costs money to send.

**Comment by Serkan-devel** [comment]
They first would need to fix their existing 2FA implementation
