### ISSUE TITLE
why minds_com has such solid system requirements for running a production? 

### ISSUE THREAD

**Issue by vetal20600** [Minds/minds#145]
What I want to do is to run minds_com software on my own server. 
According to main page ReadMe, developer needs system configuration as below to run in production:

- 3 Cassandra Nodes (Min 30gb RAM, 1TB SSD, 8 CPU)
- 1 ElasticSearch Node (Min 16GB RAM, 250GB SSD, 8 CPU) # 2 nodes are recommended for failover
- 1 Docker Machine (Min 60gb RAM, 50GB SSD, 32 CPU)

I am still figuring out what system is required to run a development for 10000+ users? Is it enough 100Gb HDD/ 10Gb memory?
What is the difference between development and production?

**Comment by Serkan-devel** [comment]
Probably that'S exactly what they run on their site

**Comment by vetal20600** [comment]
@Serkan-devel thanks for suggestion 👍 
What system requirement do you use in development?

**Comment by Serkan-devel** [comment]
@vetal20600 I'm still waiting for an answer on here https://raspberrypi.stackexchange.com/questions/91252/running-cockroachdb-on-a-raspberry-pi-2-model-b-32-bit-as-a-docker-container

**Comment by MindsGaming** [comment]
Production is Live ; Development is building. 

These specs need to be looked into, I use 45GB SDD with 4gb memory in my development version
