### ISSUE TITLE
No posts visible in development build

### ISSUE THREAD

**Issue by kwingram25** [Minds/minds#146]
I have followed the build instructions and gotten a development version of Minds running but there don't seem to be any accessible posts or channels. Is there an extra step to connect to actual data? Every tab (newsfeed, channels, etc) shows a loading spinner for a while and then comes up empty. I was hoping to work on an improvement to the boostfeed carousel but it's impossible without any posts to cycle through. Also, I seem to get logged out automatically every few minutes or so. 

Any steps to address this? Thank you!

**Comment by ottman** [comment]
This is about to be released. In meantime might have to make some manually.

**Comment by kwingram25** [comment]
I see, thank you! Will that also link to production accounts? Seems I have to create a new account each time I open it and then get logged out every few minutes

**Comment by Serkan-devel** [comment]
Wait, what will still be released?
