### ISSUE TITLE
"Cannot add existing keyspace "minds"" 

### ISSUE THREAD

**Issue by huangyingw** [Minds/minds#149]
Hi, I follow the README, and stuck with following error:

Running install
- Checking passed options: OK
- Building configuration file: OK
- Loading new configuration: OK
- Setting up data storage (ignore errors, if any): object(Cassandra\Exception\AlreadyExistsException)#405 (7) {
  ["message":protected]=>
  string(36) "Cannot add existing keyspace "minds""
  ["string":"Exception":private]=>
  string(0) ""
  ["code":protected]=>
  int(33563648)
  ["file":protected]=>
  string(52) "/var/www/Minds/engine/Core/Data/Cassandra/Client.php"
  ["line":protected]=>
  int(74)
  ["trace":"Exception":private]=>
  array(5) {
    [0]=>
    array(6) {
      ["file"]=>
      string(52) "/var/www/Minds/engine/Core/Data/Cassandra/Client.php"
      ["line"]=>
      int(74)
      ["function"]=>
      string(7) "execute"
      ["class"]=>
      string(24) "Cassandra\DefaultSession"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(1) {
        [0]=>
        string(123) "CREATE KEYSPACE minds WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'}  AND durable_writes = true;"
      }
    }
    [1]=>
    array(6) {
      ["file"]=>
      string(76) "/var/www/Minds/engine/Core/Provisioner/Provisioners/CassandraProvisioner.php"
      ["line"]=>
      int(40)
      ["function"]=>
      string(7) "execute"
      ["class"]=>
      string(32) "Minds\Core\Data\Cassandra\Client"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(1) {
        [0]=>
        string(123) "CREATE KEYSPACE minds WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'}  AND durable_writes = true;"
      }
    }
    [2]=>
    array(6) {
      ["file"]=>
      string(52) "/var/www/Minds/engine/Core/Provisioner/Installer.php"
      ["line"]=>
      int(208)
      ["function"]=>
      string(9) "provision"
      ["class"]=>
      string(56) "Minds\Core\Provisioner\Provisioners\CassandraProvisioner"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(0) {
      }
    }
    [3]=>
    array(6) {
      ["file"]=>
      string(49) "/var/www/Minds/engine/Controllers/Cli/Install.php"
      ["line"]=>
      int(54)
      ["function"]=>
      string(12) "setupStorage"
      ["class"]=>
      string(32) "Minds\Core\Provisioner\Installer"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(0) {
      }
    }
    [4]=>
    array(6) {
      ["file"]=>
      string(29) "/var/www/Minds/engine/cli.php"
      ["line"]=>
      int(51)
      ["function"]=>
      string(4) "exec"
      ["class"]=>
      string(29) "Minds\Controllers\Cli\Install"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(0) {
      }
    }
  }
  ["previous":"Exception":private]=>
  NULL
}

**Comment by MindsGaming** [comment]
Hello I am glad to try to guide you through the install process I would take a look at my blog here https://www.minds.com/blog/view/919739233351688192 for a user based install reference for the Minds code. If you are on Ubuntu you mat want to try a user sh script like the one in the blog. Feel free to tag me or comment and I will try to guide you through the set-up.
