### ISSUE TITLE
Suggestion: postinstall

### ISSUE THREAD

**Issue by m3fawner** [Minds/minds#19]
In the instructions you have run "npm install" and then "npm run build". You could utilize NPM's "postinstall" and perform the build when completed. I see you have a typings install, but you could easily append && npm run build

**Comment by markharding** [comment]
Thanks for the input! `npm run build` is a development environment only. So when we deploy on servers we don't really want to build the whole development (non aot compiled) version when we install the dependencies. Perhaps we could just say run `npm install && npm run build` in the docs to simplify?

**Comment by m3fawner** [comment]
Ah, sorry, I didn't realize the build was unnecessary for prod. You could add an additional task called "installDev" or something of the like and abstract what goes on behind the scenes.
