### ISSUE TITLE
(feat): add blocking to boost feeds

### ISSUE THREAD

**Issue by bortloff** [Minds/minds#2]
There are a few posts that are quite specifically designed to be advertisements, and I noticed that blocking their OP doesn't remove their boosted posts from headlines. Would it be possible to filter boosted posts from blocked posters from headlines?

**Comment by markharding** [comment]
We want to expand blocking to boost but we don't have a timeline yet. If you want to have a crack at it then feel free to submit a PR!

**Comment by bortloff** [comment]
I would love to! Just point me at where to start, and I'll fork, branch and make it happen!

**Comment by markharding** [comment]
Awesome. 

Boosts are loaded via https://github.com/Minds/engine/blob/master/Core/Boost/Network.php#L274. You'll want to call the ->interact() function found in https://github.com/Minds/engine/blob/master/Core/Security/ACL.php#L141.

The only concerns here really are the caching. We don't want to be hitting the database for each boost owner every time.

**Comment by bortloff** [comment]
When it comes to caching, it looks like we have the opportunity to do so in https://github.com/Minds/engine/blob/master/Core/Security/ACL/Block.php#L57, and should be able to invalidate it in https://github.com/Minds/engine/blob/master/Core/Security/ACL/Block.php#L119 and 143. As long as we are alright with the one potential where someone hammers the database by adding; checking the news feed; deleting; checking the news feed; repeat, the caching problem is solved there.

**Comment by markharding** [comment]
Yeah. We also don't want to be hitting the cache for each boost either, we want to be able to do a batch filter here.

**Comment by bortloff** [comment]
Hmm, this should be as simple as adding a owner_guid $nin [blocked_users] at https://github.com/minds/engine/blob/master/Core/Boost/Network.php#L281 . Any reason why this wouldn't work?

**Comment by markharding** [comment]
This was introduced a few weeks.
