### ISSUE TITLE
sockets repository?

### ISSUE THREAD

**Issue by brianpadraig** [Minds/minds#21]
Hey, I've been trying to install minds but the socket repository seems to be missing... anyone know how to get the sockets?  https://github.com/Minds/sockets shows a 404 error....

thanks.

**Comment by ottman** [comment]
It hasn't been released yet but will be later this year. Not required to get going.

**Comment by brianpadraig** [comment]
ok great, got it successfully installed.  thanks :)

**Comment by ottman** [comment]
Are you interested in helping with some issues? @brianpadraig

**Comment by brianpadraig** [comment]
i'm afraid i'm not an expert in all this, but i can provide feedback as i try to customize it, maybe it would help making instructions for newbies.

what i've noticed with the install out of the box, it is quite slow to load.  maybe I need a better server?  the initial script load seems to be pretty resource intensive.  just resizing the server doesn't seem to work, and seems to break it somehow.  only works when i resize it back down.

the admin user doesn't appear to have any special permissions or tools that i can find?  is there features for admins or user moderators, or does this need developed?

uploading pictures doesn't seem to work out of the box, they upload to the right directories but don't show.  probably a permissions issue, i'll look into it, might be something to add to install instructions.

**Comment by boreys** [comment]
any update on this Sockets repo? I'm interested in helping. I found some broken stuff on the front end I can do a pull request.

**Comment by duythien** [comment]
Anything update for sockets repo?

**Comment by markharding** [comment]
We will be releasing this in the new year, post some architectural changes. It should be fairly simple to create your own though, it is just a simple socket.io wrapper. 

I'll update this thread once sockets are released!

**Comment by Butonix** [comment]
You have changed the search and the blog, you will update the code on the github?

**Comment by markharding** [comment]
Just pushed!

**Comment by eva-thientran** [comment]
@markharding Are you sure? Not exits yet https://github.com/minds/sockets/tree/e3ccfd464fd5735c2decd26555c26acbefc8a130

**Comment by Serkan-devel** [comment]
Any updates on this?

**Comment by markharding** [comment]
https://github.com/Minds/sockets
