### ISSUE TITLE
(feat): A Link Showing Up Users Activity at the Notifications Page

### ISSUE THREAD

**Issue by ebonsi** [Minds/minds#29]
We need an user notification link to show to whom he/she commented, voted and posts. It is a type of memory timeline so he/she can go back to issues he/she did before. I have inserted an image as example. Thanks!
<a href="https://i.imgsafe.org/3b34749a9b.jpg"><img src="https://i.imgsafe.org/3b34749a9b.jpg" alt="User Notification Page" border="0"></a>

**Comment by ebonsi** [comment]
User request; https://www.minds.com/newsfeed/706227717049163794

**Comment by markharding** [comment]
Can we expand on this idea a bit more? Perhaps we can create some mockups and user flows?
