### ISSUE TITLE
(feat): polls

### ISSUE THREAD

**Issue by bortloff** [Minds/minds#3]
The one thing I can think of that's missing from the Minds feature set, is the ability to make poll posts. Where can we make it happen?

**Comment by markharding** [comment]
You're going to want to look at the /front and /engine repos. It would probably be better to do this inside of a plugin to kick start things. Let me know if you need a hand.. perhaps we can have a call next week?

**Comment by bortloff** [comment]
Plug-in was exactly where I thought this would start. I can start a branch for the plug-in next week and start chipping away at making it happen!

**Comment by markharding** [comment]
Check out the [Messenger](https://github.com/Minds/minds/tree/master/plugins/Messenger) and [Groups](https://github.com/Minds/minds/tree/master/plugins/Groups) plugin as guide too. Good luck!

**Comment by ChronoAndross** [comment]
@bortloff How much progress have you made with this plugin? I'm getting started on development with Minds, and I would love to contribute if possible! 
Thanks!
