### ISSUE TITLE
Navigation Tool Tips For Links 

### ISSUE THREAD

**Issue by ebonsi** [Minds/minds#30]
We need to implement the Navigation Tool Tips For Icon Links so new comers can easy navigate through Minds.
[Navigation Tool Tips Request](https://www.minds.com/newsfeed/684442057216892945)

<a href="https://i.imgsafe.org/9a6788214d.png"><img src="https://i.imgsafe.org/9a6788214d.png" alt="Navigation Tool Tips" border="0"></a>

**Comment by djbclark** [comment]
OMG please yes. This is so insanely off-putting for new users. Also for other UI elements, like the slider in the main newsfeed - I opened a bug for that before noticing this bug, see https://github.com/Minds/front/issues/24
