### ISSUE TITLE
(feat): support right to left languages

### ISSUE THREAD

**Issue by vzaidman** [Minds/minds#31]
im a web developer myself and can help with this. but i wonder how does it works.

i want to add a test whether a text was submitted "rtl" or "ltr" and add it as an attribute to message post request.

this, in turn, has to be saved on the database along with the message.

the third thing will be adding a "direction" style to the post display.

how should i start? (i cloned the whole thing)

**Comment by markharding** [comment]
I think google material components supports this now so it's something we should look into.
