### ISSUE TITLE
After setup, 'There seems to be a problem.'

### ISSUE THREAD

**Issue by pnaylor** [Minds/minds#32]
Hi, I followed the wiki instructions for installing from windows 10.

After doing vagrant up at the end initially, I was getting some 404 error at dev.minds.io.

So I ran through npm install, gulp build, gulp build.index as noted.

Now I just see:

![minds-prob](https://cloud.githubusercontent.com/assets/1429712/24069146/0777b77c-0b5e-11e7-91c4-8a6e4a99abcf.PNG)

Can't find any info yet about how this might be resolved.

Thanks, Best

**Comment by markharding** [comment]
Can you post any error logs?

**Comment by markharding** [comment]
Closing as no follow up.
