### ISSUE TITLE
(feat): ongoing subscription sync with other social media platforms

### ISSUE THREAD

**Issue by djbclark** [Minds/minds#34]
Since minds.com users can link to their Twitter and Facebook accounts, it would be great if I could just select an option somewhere that I want to follow all the people I follow on Facebook and Twitter on minds.com as well; and to have that get updated on some periodic basis automatically, so that as users I follow elsewhere create minds.com accounts and link their minds.com accounts to their Facebook and Twitter accounts, I start following them automatically on minds.com as well. 

It'd be awesome if YouTube was also added as an account type to link because a lot of YouTube creators seems to be moving partially or fully to minds.com; I definitely hear minds.com mentioned way more on YouTube than on Twitter or Facebook.

**Comment by markharding** [comment]
The best way to proceed with this would be to probably get some prototypes going. @djbclark  do you want to give it a go?
