### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by MangeStrandberg** [Minds/minds#36]
Hi,

How to install without composer?

**Comment by markharding** [comment]
Composer is needed. It's dead easy to setup and run https://getcomposer.org/

**Comment by MangeStrandberg** [comment]
Hi,

 

Thanks.

 

What do I write in composer.json to run this and it is supposed to be installed in the root of my project, right?

 

M

 

Från: Mark Harding [mailto:notifications@github.com] 
Skickat: den 10 april 2017 18:27
Till: Minds/minds <minds@noreply.github.com>
Kopia: MangeStrandberg <magnus@magnusstrandberg.se>; Author <author@noreply.github.com>
Ämne: Re: [Minds/minds] Install (#36)

 

Composer is needed. It's dead easy to setup and run https://getcomposer.org/
