### ISSUE TITLE
(feat): allow using OpenID (self-discovered) for login

### ISSUE THREAD

**Issue by strk** [Minds/minds#38]
Starting with OpenID-2.0 would be great, but OpenID-Connect with auto-discovery support would also be good. As long as users can login by just presenting an URL they control instead of a username/password pair.

See https://en.wikipedia.org/wiki/OpenID

**Comment by markharding** [comment]
@strk do you want to dig into this?

**Comment by strk** [comment]
I'm not planning to. Would first at least need to have a node
setup (would it then be compatible with GNUSocial/Mastodon/Friendica?)

**Comment by markharding** [comment]
I'm not familiar with those platforms, but I would assume that some sort of bridge would need to be created. That being said, if they support OpenID, then the federated logins *should* work.

**Comment by strk** [comment]
Sorry I meant message-level federation (ability for a Minds user
to "follow" a GNUSocial/Mastodon/Friendica/Diaspora user and
vice-versa).

Unrelated to this ticket really..

**Comment by markharding** [comment]
Let's open another task to go into more depth about that. 

I think there are definitely possibilities with webhooks etc, but to honest the UX of those tend to be really poor, and I think for the majority of end users they would be confused by seeing "@mark@node1.minds.com" in posts etc.

**Comment by strk** [comment]
Opened #47
