### ISSUE TITLE
Block Channel

### ISSUE THREAD

**Issue by Francewhoa** [Minds/minds#39]
Hi there :) It's my first time reporting a bug about Minds.com is this the correct github project? If not could you please redirect this ticket to the correct github project.

I tried minds.com for the last few weeks. So far I love it :+1: Minds is one of my favourite alternative to YouTube and Twitter.

The following is a bug report

# Summary

Blocking a Channel is not fully working. Seems like a major bug with privacy.

# Steps to reproduce
1. View any Channel page. Click on the cog wheel icon. Which is located around the top right side of the Channel. Select _"Block @USERNAME"_ option.

1. The bug is that the blocked Channel CAN still:
       1. View all your Channel content
       1. View all your Blogs. Set to "loggedin" or "Unlisted".

1. The blocked Channel can NOT
       1. Subscribe to your Channel
       1. Post comment to your Channel
       1. Post comment to your Group content
       1. Post comment to your Blogs content. Set to "loggedin" or "Unlisted".

1. Expected result is that the blocked Channel(s) should NOT be able to
       1. View all your Channel content
       1. View all your Blogs. Set to "loggedin" or "Unlisted".

If this expected result is not a bug, but by design, then this expected result is a suggestion for your consideration to improve privacy

I would be happy to contribute testing on Minds.com if needed

# Notes

Related post at https://www.minds.com/newsfeed/702273945809723412

**Comment by markharding** [comment]
Thanks for your report, be sure to checkout the[ Help & Support Group](https://www.minds.com/groups/profile/100000000000000681). 

Block currently works as expected. It is intended to stop people interacting with you, not to prevent people from viewing you public content.
