### ISSUE TITLE
Toggle "Enable advertising in your account"

### ISSUE THREAD

**Issue by Francewhoa** [Minds/minds#40]
Hi there :) 

This ticket is a bug report about Minds.com. John Ottman said he was able to reproduce this bug. The toggle switch is not working for _"Enable advertising in your account"_ at https://www.minds.com/wallet/ad-sharing
I would be happy to contribute testing on Minds.com if needed.

# Steps to reproduce
1. Sign-up for a merchant account at https://www.minds.com/wallet/merchants
2. Go to https://www.minds.com/wallet/ad-sharing
3. Click on the toggle switch next to "Enable advertising in your account". When you click that toggle doesn't switch from off to on. Nothing happens. It just remain off. Looks like a bug. Also when you click that "Enable advertising in your account" toggle, another toggle "Disable points animation" located at the bottom left side of that same page does switch from off to on. But the "Enable advertising in your account" does not switch.

# Notes
Related comment at https://www.minds.com/newsfeed/701867658223558657

**Comment by markharding** [comment]
Thanks, we've just put a fix out!

**Comment by Francewhoa** [comment]
Thanks Mark :) Confirming that toggle is fixed.
