### ISSUE TITLE
Ad Sharing APPLY Button

### ISSUE THREAD

**Issue by Francewhoa** [Minds/minds#42]
Hi there :) 

This ticket is a bug report about Minds.com
I would be happy to contribute testing on Minds.com if needed

# Summary

On the _Ad Sharing_ page the _APPLY_ button is not working

# Steps to reproduce

1. Go to https://www.minds.com/wallet/ad-sharing

1. Click on the _"Enable advertising in your account"_ toggle button. That now works. It was fix with that other ticket at #40 

1. Check the box titled _"I agree to the Minds Merchant & Ad Sharing program Terms of Service."_

1. After that nothing happens. The _APPLY_ button is still disable and not clickable. So the bug is that the user is not able to click on the _APPLY_ button. Find [that screenshot](https://cloud.githubusercontent.com/assets/119942/25307916/a6352054-275e-11e7-8f15-9ff295175809.jpg) to clarify location.

1. Expected result is that user should be able to click that _APPLY_ button

1. Things I tried but the _APPLY_ button is still not working
       1. The following help text is confusing. It seems to be referring to other field to complete. Maybe a form. But there are none on that page.
               1. Help text: _Why do you want to participate in the Minds Ad Sharing program? Please, list your other social media accounts and quantity of followers._
       1. Clear all browser cache. With hard refresh
       1. Log-out Minds.com. Then log back in. Try again.
       1. Go to https://www.minds.com/settings/general Connected with Facebook.

# Notes

Using
* Mozilla Firefox 45.8.0 
* Google Chrome Version 49.0.2623.112 (64-bit)
* Debian 7 Wheezy
* 64-bit

Related comment on "Help & Support" Group on Minds.com at https://www.minds.com/newsfeed/702617748613636112

# Screenshot
![ad---screenshot---ubertus---2017-04-22---13-04-37---wn](https://cloud.githubusercontent.com/assets/119942/25307916/a6352054-275e-11e7-8f15-9ff295175809.jpg)

With infinite Minds Love ♥

**Comment by markharding** [comment]
Thanks for your report. Have you tried the[ Help & Support Group](https://www.minds.com/groups/profile/100000000000000681)? 

This is intended, you must enter a message first for the button to become available.

**Comment by Francewhoa** [comment]
Thanks @markharding I'll try that :)

Ah I understand now. I though the following help text was only a help text not a field. I just realized it's a field I can click on it: "Why do you want to participate in the Minds Ad Sharing program? Please, list your other social media accounts and quantity of followers."

That was not clear. To reduce risk of confusion, I suggest to add that help text above that text field instead of in it.

Yup I also posted to that Help & Support Group. When I created my first ticket in GitHub I asked where to report bug. What is the easiest for you for bug report, GitHub or Help & Support Group? Assuming it's a bug report not a support request.
