### ISSUE TITLE
(feat): Clarify Help Text Ad Sharing

### ISSUE THREAD

**Issue by Francewhoa** [Minds/minds#43]
# Suggestion

On the _Ad Sharing_ page at https://www.minds.com/wallet/ad-sharing
To reduce risk of confusion, I suggest to add that help text above that text field instead of into that text field. Find [that mockup](https://cloud.githubusercontent.com/assets/119942/25308293/c811964c-2765-11e7-9682-c57a651a8da9.jpg) to clarify.

Otherwise some users might not understand that help text is actually a field which is required to be filled. The risk is that if it's not obvious some user will leave that field empty, because they don't even know it's a field. Then they will try to click the _APPLY_ button. But doing so would not work because the text field is required to activate the _APPLY_ button. Related ticket #42.

Help text: _Why do you want to participate in the Minds Ad Sharing program? Please, list your other social media accounts and quantity of followers._

# Mockup
![ad---question---mockup---ubertus---2017-04-22---14-02-00---wn](https://cloud.githubusercontent.com/assets/119942/25308293/c811964c-2765-11e7-9682-c57a651a8da9.jpg)

# Screenshot present form
![ad---screenshot---ubertus---2017-04-22---13-04-37---wn](https://cloud.githubusercontent.com/assets/119942/25307916/a6352054-275e-11e7-8f15-9ff295175809.jpg)

# Notes
Related comment at https://github.com/Minds/minds/issues/42#issuecomment-296400554
Related ticket #42

**Comment by markharding** [comment]
We're currently reworking the whole monetization section, which should be out in a couple weeks.
