### ISSUE TITLE
(?): Add Microformats2 markup to blog feeds

### ISSUE THREAD

**Issue by dissolve** [Minds/minds#44]
Most of the independant social media (Friendica, Mastodon, Known, Micro.blog, GnuSocial, Hubzilla, etc) all publish their html with microformats2 markup so that its easily processed by others.

http://microformats.org/wiki/microformats2
There are a number of parsers listed on that page as well

But for the common social web understanding of them, its best to look at
http://indieweb.org/h-feed and http://indieweb.org/h-entry

**Comment by markharding** [comment]
Can you explain a bit more on how you envision this implementation?

**Comment by dissolve** [comment]
Since the html is rendered mostly by javascript it does make things a bit more complex. 
The most useful would be to add it as additional, very minimal html in a noscript tag.
For example, a single entry could be done like this
`
&lt;noscript class="h-entry"&gt;
 
&lt;a class="u-url" href="https://www.minds.com/newsfeed/723853542418292736"&gt;
&lt;time class="dt-publish" datetime="2017-06-20T06:55:33-04:00"&gt;Jun 20, 2017, 6:55:33 AM
&lt;/time&gt; 
&lt;/a&gt; 
&lt;div class="e-content p-name"&gt; 
We just launched a few small design changes to channels, groups and the newsfeed. Let us know what you think. 
&lt;/div&gt; 

&lt;div "p-author h-card"&gt;
&lt;img class="u-photo" src="https://d3ae0shxev0cb7.cloudfront.net//icon/100000000000000063/medium/1491496785"&gt;
&lt;a "p-name u-url" href="/mark"&gt;Mark&lt;/a&gt;
&lt;/div&gt;
&lt;/noscript&gt;
`
This makes posts parsable by other social web sites, Known and Micro.blog as well as a number of smaller sites use this as their default method of communicating between sites. Its a very simple addition to do for a large step toward federating with other independent social media.

**Comment by markharding** [comment]
Thanks!
I'm guessing we might also run into issues because, right now, we have no server side rending.. so such scraping might be an issue. 
Are there no standards such as endpoints where we could return json? I think that would be a cleaner solution to accomplish this.

**Comment by dissolve** [comment]
Nothing that is widely deployed sadly.  There is some work being done on JF2 which is a json equivalent of microformats, but its not used much yet.

**Comment by dissolve** [comment]
What is the level of interest in federating with other software?  I am always interested to see more software joining the mix.

**Comment by ottman** [comment]
We are definitely interested because the principle makes sense but feel it
hasn't been implemented effectively to really spread.
