### ISSUE TITLE
(feat): Allow following activities from other networks

### ISSUE THREAD

**Issue by strk** [Minds/minds#47]
Like [Diaspora](https://diasporafoundation.org/), [Friendica](http://friendi.ca), [Mastodon](http://mastodon.social), [GNUSocial](https://www.gnu.org/software/social/) etc. 

Followup of https://github.com/Minds/minds/issues/38#issuecomment-310662138

**Comment by ottman** [comment]
Can you recommend a clean way to accomplish this without the UX issues referenced by @markharding?

> I think there are definitely possibilities with webhooks etc, but to honest the UX of those tend to be really poor, and I think for the majority of end users they would be confused by seeing "@mark@node1.minds.com" in posts etc.

**Comment by strk** [comment]
The global identifiers you are referring to is known as `Webfinger`. Some people see those identifiers as limited in that they require people to have control over a DNS record in order for them to be able to obtain an identifeir. Compare this with URL based identifiers, where a shared hosting may give more control over identities to multiple people.

This digression is just to observe that before UX there's a concept of "global identifier" to be discussed first. How does `Minds` deal with those ?

**Comment by strk** [comment]
Related ticket: #20

**Comment by strk** [comment]
Anyway, I think the UX should just allow users to define their own mapping between authoritative identifiers (an URL) and a nickname/alias.

**Comment by Serkan-devel** [comment]
https://github.com/pump-io/pump.io/issues/1 This issue needs to come forward

**Comment by Serkan-devel** [comment]
Maybe the color-schemes could differ from what social network one is connected from.

For example a slightly blue background for Mastodon users, slightly red one for GNU Social users and so on
