### ISSUE TITLE
bootstrap-ubuntu.sh fails near end of script when it attempts to create the config file

### ISSUE THREAD

**Issue by 4nanook** [Minds/minds#49]
When trying to get to run on the vBox virtual machine using Vagrant:

==> default: Installing Minds...
==> default: - Checking passed options: 
==> default: OK
==> default: - Building configuration file: 
==> default: 
==> default: cli.php: [ERROR] Configuration key `sns-secret` is not present on defaults or command line arguments
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

When I manually run the bash ./bootstrap-ubuntu.sh:

Installing Minds...
PHP Warning:  mkdir(): File exists in /var/www/Minds/bin/regenerateDevKeys.php on line 13

Installing Minds...
- Checking passed options: OK
- Building configuration file: 
cli.php: [ERROR] Configuration key `sns-secret` is not present on defaults or command line arguments

     This is on a Ubuntu 14.04.2 LTS fresh install with all the prerequisites installed as per the DOCS section of minds.org, using php 7:

     PHP 7.0.20-2~ubuntu14.04.1+deb.sury.org+1 (cli) (built: Jun 14 2017 05:55:23) ( NTS ) Copyright (c) 1997-2017 The PHP Group Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies with Zend OPcache v7.0.20-2~ubuntu14.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies

     I apologize, I do not know why github wants to strike through most of the version information above.

     Thank you very much for fixing the animations javascript thing.  This is the next place I got stuck.

     Also in case hardware matters, this is on an i7-6850 based machine with the physical host
with 128GB of RAM, running Zesty 17.04 Ubuntu.  Under that, minds.eskimo.com is a virtual machine, 6 CPU, 16GB RAM, and that is the host Vagrant / VirtualBox is running under.

     If there is any other relevant information that would be helpful, please feel free to contact me.  I am very much anxious to become a part of the Minds community.

**Comment by markharding** [comment]
The SNS config variable should not be required.. @edgebal any ideas?

**Comment by edgebal** [comment]
A fix for this is coming in the next release, in the meantime, @4nanook, you can pass an empty value for it in the last `boostrap-ubuntu.sh` command, or add:
```php
'sns-secret' => ''
```
to `engine/Core/Provisioner/Installer.php:42`

**Comment by markharding** [comment]
I think this is now resolved!

**Comment by 4nanook** [comment]
I will make another attempt soon.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.
