### ISSUE TITLE
Trying to install having issues

### ISSUE THREAD

**Issue by tedbakers** [Minds/minds#5]
Hi,

I was trying to set up a version of minds on an ubuntu server so I could start to understand it.

I have installed (following this guide https://minds.org/docs/install/download.html) all the pre-requisites (including optional) and I have tried to git (git clone https://github.com/minds/minds.git --recursive). This requires a login when it gets to the engine module. My login for here doesn't work so this engine download fails.

Then when I run bin/bootstrap-ubuntu.sh after changing the folder name from minds to Minds and giving permissions I receive error...

PHP Warning:  require_once(/var/www/Minds/bin/../engine/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/Minds/bin/cli.php on line 9
PHP Fatal error:  require_once(): Failed opening required '/var/www/Minds/bin/../engine/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/Minds/bin/cli.php on line 9

Which makes sense as that file is indeed missing so I obtained the https://github.com/Minds/engine.git and placed it in engine under Minds but that made no difference.

Any ideas how I fix this issue?

Any help greatly appreciated.

Thanks

Ted

**Comment by markharding** [comment]
Hey Ted.

The submodules should have populated with the `--recursive` param on the clone.. Is your /front dir empty too? The error you're getting sounds like you've not configured the dependencies. Inside the /engine dir, run `composer install`. 

It would be great to hop on a skype/hangout with you to talk through your setup process so we can improve the docs! Skype: kramnorth, Hangouts: mark@minds.com

**Comment by tedbakers** [comment]
Hi, 

Thanks for your prompt reply. I will add you in Hangouts. I am from the UK but I live in Thailand so I am GMT + 6 (it's 6am currently in the UK and midday here) so not sure when convenient times are.

As for the setup process I believe I have configured all the pre-reqs correctly, all required (cassandra, nginx, php 7, RabbitMQ, openSSL) are installed and running where applicable. I get no errors regarding these when running the bin/bootstrap-ubuntu.sh and I see it verifying them. I have installed a certificate and turned on SSL which is working.

The problem seems to be that it can't clone the engine folder. This engine folder is not present so I cannot enter it torun 'composer install'. When doing the git clone it gets to engine part and then asks for username and password for https://github.com. My username and password don't work.

The front folder however is present but empty.

Thanks

Ted

**Comment by otwstephanie** [comment]
The subrepos are pointing at the internal versions, a simple fix ted is to cd into your minds directory after you clone that  execute "git clone https://github.com/minds/front.git"   and then when finishes also do "git clone https://github.com/minds/engine.git"  (no quotes)

**Comment by tedbakers** [comment]
Thanks @otwstephanie. I had previously tried that but not since my initial attempt.

So, I now have the engine and front cloned and i run "composer install" in engine and I get the screenshot below which again seems to require a login

![image](https://cloud.githubusercontent.com/assets/16678784/17739421/e9e8d880-648c-11e6-8f06-f5817d859344.png)

Any ideas?

Thanks

Ted

**Comment by ottman** [comment]
We will get back to you soon on this! Thanks

**Comment by tedbakers** [comment]
Thanks

**Comment by otwstephanie** [comment]
@markharding had said you didn't need the "minds-php-sdk", and could comment it out, so just remove it from the requirements. Had asked about this on the minds support page at minds site.

**Comment by tedbakers** [comment]
Thanks again @otwstephanie. I have commented that out and have now got that through successfully and after much pain with versions the npm install and gulp of the front.

I now run the bin/bootstrap-ubuntu.sh and receive:
![image](https://cloud.githubusercontent.com/assets/16678784/17805313/dd22697a-65f6-11e6-9f2b-c0ec2b51943a.png)

I have confirmed cassandra is running and listening on port 9160
![image](https://cloud.githubusercontent.com/assets/16678784/17805339/00473aca-65f7-11e6-95e1-746762f88a62.png)

I have tried version 2.1 of cassandra and letting the install script update it to 2.2 and I have tried version 3.7 of cassandra and both give the same results. It does say 2.2 or higher is acceptable. 

I have run out of ideas and feel I've been going round in circles on the internet. Is there some cassandra configuration/setting I am missing?

Thanks

Ted

**Comment by bortloff** [comment]
Hey guys, the sockets submodule isn't available. Any way we can get access to it for installation?

**Comment by otwstephanie** [comment]
Which version of node / nodejs did you end up using to get it to work. I have a feeling that be where my problems are lying, having similar issues not the same but, related.

**Comment by markharding** [comment]
You should use at least node 5. Can you open a new ticket and provide any
error logs?

**Comment by tedbakers** [comment]
@otwstephanie  I still haven't got it running successfully but i used 6.4, plan to get back to trying as soon as i have time

**Comment by whisere** [comment]
@tedbakers  see https://github.com/Minds/minds/issues/6
try check cassandra connection with:
nodetool status
cqlsh
and check cassandra log at /var/log/cassandra

**Comment by bortloff** [comment]
Alright, I decided that there were a number of problems in getting the development environment created. Notably, that the intent of using vagrant as an always-reproducible development environment was broken when it required too many things to be done outside of vagrant to make it work.

I've got the relevant changes added to the following:

`https://github.com/bortloff/minds/tree/dev_env_fixes`
`https://github.com/bortloff/front/tree/dev_env_fixes`
`https://github.com/bortloff/engine/tree/dev_env_fixes`

Theoretically, all you should need to do is the following:
`git clone -b dev_env_fixes https://github.com/bortloff/minds`
`cd minds; vagrant up`

From here, this should automatically create the entire environment without any fuss. Once you add dev.minds.io to your hosts file as in the docs, you should be able to see a working site.

I'm going to add: This install seems to require a minimum of a 8-thread CPU and 2GB RAM. I just barely got under the 10s sleep at the end of the provisioning script waiting for Cassandra to finish loading. You may see a stall in the middle of the provisioning; This is "normal", npm is just thinking really hard and not telling you about it.

_(PS: There are so many warnings during the install, that it has quite a ways to go before being considered "fully working", but at least we got somewhere)_

**Comment by whisere** [comment]
Thank you. will try this later. it did keep running out of memory when I tried installing under vagrant. I seem to have installed it successfully outside of vagrant, but the whole minds-homepage block is not showing, see the attachment below. No error report in nginx log, but the browser had warning: 
modal service constructed
app.js?...1365572 (line 39)
The PLATFORM_PIPES provider and CompilerConfig.platformPipes is deprecated. Add the pipes to an NgModule instead! (Pipes: AbbrPipe,DomainPipe,TagsPipe,SanitizePipe,SafePipe)
Any idear?

**Comment by whisere** [comment]
![screenshot from 2016-08-26 15_05_34](https://cloud.githubusercontent.com/assets/2360494/18456824/8505af54-7997-11e6-9b42-93b9a10280b5.png)

**Comment by bortloff** [comment]
I don't quite know, @whisere, but after merging minds/engine:master into my branch, it looks like something _else_ broke right at cli.php.

To be frank, there are an unholy number of warnings during install. I got it far enough to start working, but there are still a huge number of problems that need to be worked out.

**Comment by ottman** [comment]
You are brave pioneers. Thanks for your energy here and we will be back to you.

**Comment by bortloff** [comment]
@ottman It's a dirty job, but someone's gotta do it. https://www.youtube.com/watch?v=LQhX8PbNUWI

**Comment by ottman** [comment]
How are you all getting along?
