### ISSUE TITLE
gulp build has an error in build.sass

### ISSUE THREAD

**Issue by 4nanook** [Minds/minds#50]
10:24:06] Starting 'build.sass'...
Error in plugin 'sass'
Message:
    app/stylesheets/components/mature.scss
Error: Undefined variable: "$minds-padding".
        on line 128 of app/stylesheets/components/mature.scss
>>     top: $minds-padding;
   ---------^

[10:24:23] Finished 'build.sass' after 18 s

**Comment by markharding** [comment]
Thanks, this is a duplicate of front/issues/17
