### ISSUE TITLE
Image URLS not apt for downloading.

### ISSUE THREAD

**Issue by madprops** [Minds/minds#52]
In Facebook I download images very regularly. Just tried to download one in Minds and it got saved with the name "SaveImageRouter.xlarge". This is inconvenient for 2 reasons. No unique name, so saving them more than 1 image will prompt the user to what to do. No extension, the image doesn't work without completely rewriting the file name.

I think being able to download images easily is crucial.

**Comment by markharding** [comment]
Having trouble replicating this. Please feel free to open again with some more debug information.
