### ISSUE TITLE
Confusing after first Boost

### ISSUE THREAD

**Issue by madprops** [Minds/minds#53]
I boosted a post with 200 points. I got confused because first of all I got a notification saying "200 views for your post is awaiting approval.", so I go to the post and there's no indication it has been boosted (except that it "charged" me the 200 points), it actually shows the "Boost" button still, as if I could do another boost, or worse, giving me the impression (this plus the notification) that I didn't actually boost it and that I have to for some reason approve the boost somwhere (which I can't find).

**Comment by ottman** [comment]
True. We can clarify
