### ISSUE TITLE
Privacy of post

### ISSUE THREAD

**Issue by herry2016** [Minds/minds#55]
All social network provide post privacy level so introduce the post privacy and profile privacy as wwll

**Comment by markharding** [comment]
Hi Herry, Please checkout https://www.minds.com/groups/profile/100000000000000681.

**Comment by herry2016** [comment]
I want to see admin penal please saw me if possible

On Jul 24, 2017 9:08 PM, "Mark Harding" <notifications@github.com> wrote:

Hi Herry, Please checkout https://www.minds.com/groups/
profile/100000000000000681.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Minds/minds/issues/55#issuecomment-317462885>, or mute
the thread
