### ISSUE TITLE
Minds git install prompting for username.  !???

### ISSUE THREAD

**Issue by g-reno** [Minds/minds#58]
$ git clone https://github.com/minds/minds.git --recursive
Cloning into 'minds'...
remote: Counting objects: 157892, done.
remote: Compressing objects: 100% (86/86), done.
remote: Total 157892 (delta 91), reused 123 (delta 81), pack-reused 157722
Receiving objects: 100% (157892/157892), 221.06 MiB | 5.67 MiB/s, done.
Resolving deltas: 100% (99294/99294), done.
Submodule 'engine' (https://github.com/minds/engine-internal.git) registered for path 'engine'
Submodule 'front' (https://github.com/minds/front-internal.git) registered for path 'front'
Submodule 'sockets' (https://github.com/minds/sockets.git) registered for path 'sockets'
Cloning into 'engine'...
Username for 'https://github.com':

**Comment by markharding** [comment]
Please run `sh ./init.sh`. --recursive is for the internal repos.

Related to #5.

**Comment by g-reno** [comment]
Thanks.  I'm assuming this is correct:

minds]$ sh ./init.sh --recursive
Already up-to-date.
Cloning into 'front'...
remote: Counting objects: 12779, done.
remote: Compressing objects: 100% (97/97), done.
remote: Total 12779 (delta 35), reused 38 (delta 12), pack-reused 12670
Receiving objects: 100% (12779/12779), 70.10 MiB | 5.66 MiB/s, done.
Resolving deltas: 100% (8744/8744), done.
Cloning into 'engine'...
remote: Counting objects: 7946, done.
remote: Total 7946 (delta 0), reused 0 (delta 0), pack-reused 7946
Receiving objects: 100% (7946/7946), 1.51 MiB, done.
Resolving deltas: 100% (5060/5060), done.

**Comment by markharding** [comment]
You're best looking at the readme -> https://github.com/Minds/minds#download-and-provisioning

```
git clone git@github.com:minds/minds.git
cd minds
sh ./init.sh
vagrant up
```

**Comment by g-reno** [comment]
Almost there:
minds]$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 80 (guest) => 8800 (host) (adapter 1)
    default: 8010 (guest) => 8810 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 4.3.36
    default: VirtualBox Version: 4.2
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Exporting NFS shared folders...
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
[sudo] password for <USER>

But the users password does not work here and it just reprompts again until it eventually fails from too many tries.
What password does vagrant want?

**Comment by markharding** [comment]
That would be your local machine password.

**Comment by g-reno** [comment]
Ok, I think this was a Centos issue.  Sudo was not configured for that user.
