### ISSUE TITLE
(bug): Cassandra PHP library not installing

### ISSUE THREAD

**Issue by g-reno** [Minds/minds#59]
==> default: CMake Warning at cmake/modules/CppDriver.cmake:242 (message):
==> default:   Could not find zlib, try to set the path to zlib root folder in the system
==> default:   variable ZLIB_ROOT_DIR
==> default: Call Stack (most recent call first):
==> default:   CMakeLists.txt:122 (CassUseZlib)
==> default: 
==> default: 
==> default: CMake Warning at cmake/modules/CppDriver.cmake:243 (message):
==> default:   zlib libraries will not be linked into build
==> default: Call Stack (most recent call first):
==> default:   CMakeLists.txt:122 (CassUseZlib)

-------------------------------------
==> default: In file included from /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.cpp:22:0:
==> default: /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ring_buffer_bio.hpp: In static member function ‘static cass::rb::RingBuffer* cass::rb::RingBufferBio::from_bio(BIO*)’:
==> default: /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ring_buffer_bio.hpp:59:40: error: invalid use of incomplete type ‘BIO {aka struct bio_st}’
==> default:      return static_cast<RingBuffer*>(bio->ptr);
==> default:                                         ^
==> default: In file included from /usr/include/openssl/crypto.h:31:0,
==> default:                  from /usr/include/openssl/comp.h:16,
==> default:                  from /usr/include/openssl/ssl.h:47,
==> default:                  from /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.hpp:21,
==> default:                  from /home/vagrant/php-driver/lib/cpp-driver/src/ssl.hpp:108,
==> default:                  from /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.cpp:17:
==> default: /usr/include/openssl/ossl_typ.h:79:16: error: forward declaration of ‘BIO {aka struct bio_st}’
==> default:  typedef struct bio_st BIO;
==> default:                 ^
==> default: In file included from /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.cpp:27:0:
==> default: /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.cpp: In function ‘int cass::SSL_CTX_use_certificate_chain_bio(SSL_CTX*, BIO*)’:
==> default: /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.cpp:149:12: error: ‘SSL_F_SSL_CTX_USE_CERTIFICATE_CHAIN_FILE’ was not declared in this scope
==> default:      SSLerr(SSL_F_SSL_CTX_USE_CERTIFICATE_CHAIN_FILE,ERR_R_PEM_LIB);
==> default:             ^
==> default: /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.cpp:168:12: error: invalid use of incomplete type ‘SSL_CTX {aka struct ssl_ctx_st}’
==> default:      if (ctx->extra_certs != NULL) {
==> default:             ^
==> default: In file included from /usr/include/openssl/crypto.h:31:0,
==> default:                  from /usr/include/openssl/comp.h:16,
==> default:                  from /usr/include/openssl/ssl.h:47,
==> default:                  from /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.hpp:21,
==> default:                  from /home/vagrant/php-driver/lib/cpp-driver/src/ssl.hpp:108,
==> default:                  from /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.cpp:17:
==> default: /usr/include/openssl/ossl_typ.h:145:16: error: forward declaration of ‘SSL_CTX {aka struct ssl_ctx_st}’
==> default:  typedef struct ssl_ctx_st SSL_CTX;
==> default:                 ^
==> default: /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.cpp:169:27: error: invalid use of incomplete type ‘SSL_CTX {aka struct ssl_ctx_st}’
==> default:        sk_X509_pop_free(ctx->extra_certs, X509_free);
==> default:                            ^
==> default: In file included from /usr/include/openssl/crypto.h:31:0,
==> default:                  from /usr/include/openssl/comp.h:16,
==> default:                  from /usr/include/openssl/ssl.h:47,
==> default:                  from /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.hpp:21,
==> default:                  from /home/vagrant/php-driver/lib/cpp-driver/src/ssl.hpp:108,
==> default:                  from /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.cpp:17:
==> default: /usr/include/openssl/ossl_typ.h:145:16: error: forward declaration of ‘SSL_CTX {aka struct ssl_ctx_st}’
==> default:  typedef struct ssl_ctx_st SSL_CTX;
==> default:                 ^
==> default: /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.cpp:170:10: error: invalid use of incomplete type ‘SSL_CTX {aka struct ssl_ctx_st}’
==> default:        ctx->extra_certs = NULL;
==> default:           ^
==> default: In file included from /usr/include/openssl/crypto.h:31:0,
==> default:                  from /usr/include/openssl/comp.h:16,
==> default:                  from /usr/include/openssl/ssl.h:47,
==> default:                  from /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.hpp:21,
==> default:                  from /home/vagrant/php-driver/lib/cpp-driver/src/ssl.hpp:108,
==> default:                  from /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.cpp:17:
==> default: /usr/include/openssl/ossl_typ.h:145:16: error: forward declaration of ‘SSL_CTX {aka struct ssl_ctx_st}’
==> default:  typedef struct ssl_ctx_st SSL_CTX;
==> default:                 ^
==> default: /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.cpp: In static member function ‘static cass::OpenSslVerifyIdentity::Result cass::OpenSslVerifyIdentity::match_common_name_ipaddr(X509*, const string&)’:
==> default: /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.cpp:281:57: error: ‘unsigned char* ASN1_STRING_data(ASN1_STRING*)’ is deprecated (declared at /usr/include/openssl/asn1.h:553) [-Werror=deprecated-declarations]
==> default:        const char* common_name = reinterpret_cast<char*>(ASN1_STRING_data(str));
==> default:                                                          ^
==> default: /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.cpp:281:77: error: ‘unsigned char* ASN1_STRING_data(ASN1_STRING*)’ is deprecated (declared at /usr/include/openssl/asn1.h:553) [-Werror=deprecated-declarations]
==> default:        const char* common_name = reinterpret_cast<char*>(ASN1_STRING_data(str));
==> default:                                                                              ^
==> default: /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.cpp: In static member function ‘static cass::OpenSslVerifyIdentity::Result cass::OpenSslVerifyIdentity::match_common_name_dns(X509*, const string&)’:
==> default: /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.cpp:312:57: error: ‘unsigned char* ASN1_STRING_data(ASN1_STRING*)’ is deprecated (declared at /usr/include/openssl/asn1.h:553) [-Werror=deprecated-declarations]
==> default:        const char* common_name = reinterpret_cast<char*>(ASN1_STRING_data(str));
==> default:                                                          ^
==> default: /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.cpp:312:77: error: ‘unsigned char* ASN1_STRING_data(ASN1_STRING*)’ is deprecated (declared at /usr/include/openssl/asn1.h:553) [-Werror=deprecated-declarations]
==> default:        const char* common_name = reinterpret_cast<char*>(ASN1_STRING_data(str));
==> default:                                                                              ^
==> default: /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.cpp: In static member function ‘static cass::OpenSslVerifyIdentity::Result cass::OpenSslVerifyIdentity::match_subject_alt_names_ipadd(X509*, const cass::Address&)’:
==> default: /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.cpp:352:29: error: ‘unsigned char* ASN1_STRING_data(ASN1_STRING*)’ is deprecated (declared at /usr/include/openssl/asn1.h:553) [-Werror=deprecated-declarations]
==> default:          unsigned char* ip = ASN1_STRING_data(str);
==> default:                              ^
==> default: /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.cpp:352:49: error: ‘unsigned char* ASN1_STRING_data(ASN1_STRING*)’ is deprecated (declared at /usr/include/openssl/asn1.h:553) [-Werror=deprecated-declarations]
==> default:          unsigned char* ip = ASN1_STRING_data(str);
==> default:                                                  ^
==> default: /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.cpp: In static member function ‘static cass::OpenSslVerifyIdentity::Result cass::OpenSslVerifyIdentity::match_subject_alt_names_dns(X509*, const string&)’:
==> default: /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.cpp:389:59: error: ‘unsigned char* ASN1_STRING_data(ASN1_STRING*)’ is deprecated (declared at /usr/include/openssl/asn1.h:553) [-Werror=deprecated-declarations]
==> default:          const char* common_name = reinterpret_cast<char*>(ASN1_STRING_data(str));
==> default:                                                            ^
==> default: /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.cpp:389:79: error: ‘unsigned char* ASN1_STRING_data(ASN1_STRING*)’ is deprecated (declared at /usr/include/openssl/asn1.h:553) [-Werror=deprecated-declarations]
==> default:          const char* common_name = reinterpret_cast<char*>(ASN1_STRING_data(str));
==> default:                                                                                ^
==> default: /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.cpp: At global scope:
==> default: /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.cpp:114:13: error: ‘void cass::crypto_locking_callback(int, int, const char*, int)’ defined but not used [-Werror=unused-function]
==> default:  static void crypto_locking_callback(int mode, int n, const char* file, int line) {
==> default:              ^
==> default: /home/vagrant/php-driver/lib/cpp-driver/src/ssl/ssl_openssl_impl.cpp:130:22: error: ‘long unsigned int cass::crypto_id_callback()’ defined but not used [-Werror=unused-function]
==> default:  static unsigned long crypto_id_callback() {
==> default:                       ^
==> default: cc1plus: all warnings being treated as errors
==> default: make[2]: *** [CMakeFiles/cpp-driver.dir/src/ssl/ssl_openssl_impl.cpp.o] Error 1
==> default: make[1]: *** [CMakeFiles/cpp-driver.dir/all] Error 2
==> default: make: *** [all] Error 2

--------------------------------
==> default: /tmp/vagrant-shell: line 109: node: command not found
==> default: dpkg: error: --compare-versions takes three arguments: <version> <relation> <version>
==> default: 

---------------------------------
==> default: 2017-08-02 22:14:29 (610 KB/s) - ‘composer-setup.php’ saved [305728/305728]
==> default: PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/cassandra.so' - /usr/lib/php/20151012/cassandra.so: cannot open shared object file: No such file or directory in Unknown on line 0

---------------------------------
==> default: Error connecting to 127.0.0.1: LegacyCassandra\InvalidRequestException: 
==> default: Error connecting to 127.0.0.1: LegacyCassandra\InvalidRequestException: 
==> default: PHP Fatal error:  Uncaught Error: Class 'Cassandra' not found in /var/www/Minds/engine/Core/Data/Cassandra/Client.php:23
==> default: Stack trace:
==> default: #0 /var/www/Minds/engine/Core/Data/Client.php(34): Minds\Core\Data\Cassandra\Client->__construct(Array)
==> default: #1 /var/www/Minds/engine/Core/Provisioner/Provisioners/CassandraProvisioner.php(85): Minds\Core\data\Client::build('\\Minds\\Core\\Dat...', Array)
==> default: #2 /var/www/Minds/engine/Core/Provisioner/Installer.php(181): Minds\Core\Provisioner\Provisioners\CassandraProvisioner->provision(Array)
==> default: #3 /var/www/Minds/engine/Controllers/Cli/Install.php(41): Minds\Core\Provisioner\Installer->setupStorage()
==> default: #4 /var/www/Minds/bin/cli.php(50): Minds\Controllers\Cli\Install->exec()
==> default: #5 {main}
==> default:   thrown in /var/www/Minds/engine/Core/Data/Cassandra/Client.php on line 23

**Comment by markharding** [comment]
Something looks to have changed with the Cassandra driver install (https://github.com/datastax/php-driver)

**Comment by g-reno** [comment]
Is the Cassandra problem related to this statement on DataStax?:

About Apache Cassandra

DataStax no longer provides the DataStax Community version of Apache Cassandra™ or the DataStax Distribution of Apache Cassandra. See DataStax support for Apache Cassandra.

**Comment by markharding** [comment]
No, it's a build error.

**Comment by g-reno** [comment]
https://datastax-oss.atlassian.net/browse/CPP-484
https://datastax-oss.atlassian.net/browse/CPP-438

**Comment by g-reno** [comment]
==> default: -- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.0f")

Something is dragging in openssl 1.1.
Trusty is supposed to have openssl 1.0.1f

Bad PPA?

**Comment by g-reno** [comment]
PPA issue about libssl / openssl:
https://github.com/oerdnj/deb.sury.org/issues/643

**Comment by g-reno** [comment]
Today I tried holding the openssl package.
I placed a hold on openssl in bin/bootstrap-ubuntu.sh
But this did not appear to work and caused other errors:

> ==> default: OK
> ==> default: openssl was already set on hold.
> ==> default: Ign http://debian.datastax.com stable InRelease
> ==> default: Hit http://security.ubuntu.com trusty-security InRelease
> ==> default: Get:1 http://ppa.launchpad.net trusty InRelease [20.9 kB]
> 
> --------------------------------------------
> ==> default: The following held packages will be changed:
> ==> default:   openssl
> ==> default: The following packages will be upgraded:
> ==> default:   libgd3 libpcre3 openssl
> ==> default: 3 upgraded, 124 newly installed, 0 to remove and 3 not upgraded.
> ==> default: Need to get 119 MB of archives.
> ==> default: After this operation, 323 MB of additional disk space will be used.
> ==> default: E: There are problems and -y was used without --force-yes
> ==> default: cp: cannot stat ‘/var/www/Minds/conf/nginx-site.conf’: No such file or directory
> ==> default: cp: cannot stat ‘/var/www/Minds/conf/nginx.conf’: No such file or directory
> ==> default: sed: can't read /etc/php/7.0/fpm/php.ini: No such file or directory
> ==> default: sed: can't read /etc/cassandra/cassandra.yaml: No such file or directory
> ==> default: sed: can't read /etc/cassandra/cassandra.yaml: No such file or directory
> ==> default: sed: can't read /etc/cassandra/cassandra.yaml: No such file or directory
> ==> default: sed: can't read /etc/cassandra/cassandra.yaml: No such file or directory
> ==> default: sed: can't read /etc/cassandra/cassandra.yaml: No such file or directory
> ==> default: sed: can't read /etc/cassandra/cassandra.yaml: No such file or directory
> 
> ---------------------------------------------
> ==> default: The following held packages will be changed:
> ==> default:   openssl
> ==> default: The following packages will be upgraded:
> ==> default:   libpcre3 openssl
> ==> default: 2 upgraded, 59 newly installed, 0 to remove and 4 not upgraded.
> ==> default: Need to get 39.1 MB of archives.
> ==> default: After this operation, 118 MB of additional disk space will be used.
> ==> default: E: There are problems and -y was used without --force-yes
> ==> default: /tmp/vagrant-shell: line 84: git: command not found
> ==> default: /tmp/vagrant-shell: line 85: cd: php-driver: No such file or directory
> ==> default: /tmp/vagrant-shell: line 86: git: command not found
> ==> default: /tmp/vagrant-shell: line 87: cd: ext: No such file or directory
> 
> -----------------------------------------
> ==> default: php: symbol lookup error: php: undefined symbol: pcre_jit_exec
> ==> default: /tmp/vagrant-shell: line 128: cd: /var/www/Minds/engine: No such file or directory
> ==> default: /tmp/vagrant-shell: line 129: composer: command not found
> ==> default: /tmp/vagrant-shell: line 130: cd: OLDPWD not set
> ==> default: Installing Minds...
> ==> default: php: symbol lookup error: php: undefined symbol: pcre_jit_exec
> ==> default: php: symbol lookup error: php: undefined symbol: pcre_jit_exec
> The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.
>

**Comment by g-reno** [comment]
Here's what I see as the problem.
This oerdnj PPA is targeting regular Ubuntu releases which spells trouble for any project dedicated to LTS releases such as Minds.
The solution is to either ask the PPA provider to provide an LTS focused PPA or
to switch to using regular Ubuntu releases with their fast-paced update schedules.

**Comment by g-reno** [comment]
Tried with ubuntu/xenial64 today to see if newer LTS would help.  It didn't.
Basically same build errors as with trusty.

**Comment by djonatanb** [comment]
Hi, I got here by searching for the same problem but in a different project.
This is what I did to fix it:
``
git clone git://git.openssl.org/openssl.git cd openssl
cd openssl
git tag -l
git checkout tags/OpenSSL_1_0_2k
./config shared -fPIC --prefix=/usr/local --openssldir=/usr/local/ssl
make
make depend
make test
sudo make install
sudo ln -s /usr/local/openssl/bin/openssl/bin/openssl /usr/bin
``

**Comment by markharding** [comment]
This should be solved with #1a9a6cc
