### ISSUE TITLE
installation notes

### ISSUE THREAD

**Issue by whisere** [Minds/minds#6]
Some notes re installations (& waiting for keyspaces infomation):

Under Ubuntu 14.04:

------------------------------------------

run 'npm install' under /front

Problem: /usr/bin/env: node: No such file or directory

Solved by running:

sudo ln -s /usr/bin/nodejs /usr/bin/node

-----------------------------------------
run 'composer install' under /engine
Problem:
    - Installation request for mongodb/mongodb 1.0.2 -> satisfiable by mongodb/mongodb[1.0.2].
    - mongodb/mongodb 1.0.2 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
Reason:
PHP mongodb extension is not installed for 7.1 under ubuntu 14.04
Solved by:
remove php 7.1, use php 7.0

change php_version="7.1" to php_version="7.0" in bootstrap-ubuntu.sh under /bin

change  server unix:/run/php/php7.1-fpm.sock; to  server unix:/run/php/php7.0-fpm.sock; in nginx.conf under /conf

----------------------
run 'composer install' under /engine
Problem:
                                                                              
  [RuntimeException]                                                           
  Failed to execute git clone --no-checkout 'https://:***@github.com/m  
  inds/minds-php-sdk.git' '/home/admin/Documents/Minds/minds/engine/vendo  
  r/minds/minds-php-sdk' && cd '/home/admin/Documents/Minds/minds/engine/  
  vendor/minds/minds-php-sdk' && git remote add composer 'https://:***  
  @github.com/minds/minds-php-sdk.git' && git fetch composer                   
  Cloning into '/home/admin/Documents/Minds/minds/engine/vendor/minds/min  
  ds-php-sdk'...                                                               
  remote: Repository not found.                                                
  fatal: repository 'https://:***@github.com/minds/minds-php-sdk.git/'  
   not found 

Solved by:
delete
      "minds/minds-php-sdk": "dev-master@dev",
      repository for minds-php-sdk
from composer.json and delete composer.lock
rerun composer install
------------------------------------------------------------------------------------------------

run 'gulp build && gulp build.indexfront' under /front

Problem:
Error: EPERM, chmod '/home/admin/Documents/Minds/minds/front/app/src/plugins/Groups/card'
Solved by run:
sudo  npm install -g npm-check-updates
sudo npm install npm@latest -g
sudo npm update
sudo chown admin -R front
cd front 

gulp build && gulp build.index

open http://localhost/minds/ or http://10.54.0.111/ under Vagrant

--------------------------------------------------------------------------------------------

Problem:

nginx error log:

[Thu Aug 18 10:08:58.311591 2016] [:error] [pid 2889] [client 127.0.0.1:38308] Error connecting to 127.0.0.1: cassandra\\InvalidRequestException:
[Thu Aug 18 10:08:58.312365 2016] [:error] [pid 2889] [client 127.0.0.1:38308] Error connecting to 127.0.0.1: cassandra\\InvalidRequestException:
[Thu Aug 18 10:08:58.313457 2016] [:error] [pid 2889] [client 127.0.0.1:38308] Error connecting to 127.0.0.1: cassandra\\InvalidRequestException:
[Thu Aug 18 10:08:58.313890 2016] [:error] [pid 2889] [client 127.0.0.1:38308] Error connecting to 127.0.0.1: cassandra\\InvalidRequestException:
[Thu Aug 18 10:08:58.314410 2016] [:error] [pid 2889] [client 127.0.0.1:38308] Exception #1471478938: exception 'InstallationException' with message 'Unable to handle this request. This site  is not configured or the database is down.' in /var/www/html/minds/engine/lib/configuration.php:531\nStack trace:\n#0 /var/www/html/minds/engine/lib/elgglib.php(2056): _elgg_load_site_config()\n#1 [internal function]: _elgg_engine_boot('boot', 'system', NULL)\n#2 /var/www/html/minds/engine/Core/Events/Dispatcher.php(131): call_user_func_array('_elgg_engine_bo...', Array)\n#3 /var/www/html/minds/engine/lib/elgglib.php(623): Minds\\Core\\Events\\Dispatcher::trigger('boot', 'elgg/event/syst...', NULL, true)\n#4 /var/www/html/minds/engine/Core/Minds.php(74): elgg_trigger_event('boot', 'system')\n#5 /var/www/html/minds/engine/start.php(23): Minds\\Core\\Minds->start()\n#6 /var/www/html/minds/index.php(3): require_once('/var/www/html/m...')\n#7 {main}

Solved by

add and change in settings.php

$CONFIG->installed = true;
$CONFIG->path = '/var/www/Minds/';
$CONFIG->plugins_path = '/var/www/Minds/plugins/';
$CONFIG->pluginspath = '/var/www/Minds/plugins/';
$CONFIG->dataroot = '/home/vagrant/tmpdata/'; //create the folder
$CONFIG->default_site = '1';
$CONFIG->site_id = '1';
$CONFIG->__site_secret__ = '8c4e4baf87bb8681e67f3668b02fb86b';

$CONFIG->site_guid = '0';
$CONFIG->site_name = 'Test minds';
$CONFIG->site_url = '127.0.0.1';
$CONFIG->wwwroot = 'localhost/Minds';
$CONFIG->site_email = '';
$CONFIG->site_description = 'Test12';

-------------------------------------------------------------------------------------------------

Problem:

PHP message: Error connecting to 127.0.0.1: Thrift\Exception\TException: TSocket: Could not connect to 127.0.0.1:9160 (Connection refused [111])
PHP message: Error connecting to 127.0.0.1: Thrift\Exception\TException: TSocket: Could not connect to 127.0.0.1:9160 (Connection refused [111])
PHP message: Error connecting to 127.0.0.1: Thrift\Exception\TException: TSocket: Could not connect to 127.0.0.1:9160 (Connection refused [111])
PHP message: PHP WARNING: 2016-08-26 05:58:09 (UTC): "socket_connect(): unable to connect [111]: Connection refused" in file /var/www/Minds/engine/vendor/duoshuo/php-cassandra/src/Connection/Socket.php (line 57)
PHP message: PHP WARNING: 2016-08-26 05:58:09 (UTC): "Declaration of Minds\Core\Data\indexes::get($key_id, array $options = Array) should be compatible with Minds\Core\Data\Call::get($offset = '', $limit = 10)" in file /var/www/Minds/engine/Core/Data/indexes.php (line 0)
PHP message: Error connecting to 127.0.0.1: Thrift\Exception\TException: TSocket: Could not connect to 127.0.0.1:9160 (Connection refused [111])
PHP message: Error connecting to 127.0.0.1: Thrift\Exception\TException: TSocket: Could not connect to 127.0.0.1:9160 (Connection refused [111])" while reading response header from upstream, client: 10.54.0.1, server: _, request: "GET /api/v1/blog/featured?limit=4 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "10.54.0.111", referrer: "http://10.54.0.111/"

Solved by install
php-curl
elasticsearch
restart cassandra
check:
nodetool status

------------------------------------------------------------------------------------------------------------
Cassandra keyspaces data and structure need to be set up 

See engine/settings.php:
$CONFIG->cassandra = (object) [
    'keyspace'    => 'minds',
    'servers'     => [ '127.0.0.1' ],
    'cql_servers' => [ '127.0.0.1:9042' ]
];

and engine/Spec/bootstrap.php:
$CONFIG->cassandra->keyspace = 'phpspec';
$CONFIG->cassandra->servers = array('127.0.0.1');
$CONFIG->cassandra->cql_servers = array('127.0.0.1:9042');

cqlsh> CREATE KEYSPACE minds WITH REPLICATION = { 'class' : 'NetworkTopologyStrategy', 'datacenter1' : 3 };
cqlsh> CREATE KEYSPACE phpspec WITH REPLICATION = { 'class' : 'NetworkTopologyStrategy', 'datacenter1' : 3 };

--------------------------------------------------------------------------------
Waiting for keyspaces information for next step

**Comment by whisere** [comment]
![screenshot from 2016-08-26 15 04 53](https://cloud.githubusercontent.com/assets/2360494/18071611/afd1c270-6e9a-11e6-9ec3-628175456e66.png)

**Comment by whisere** [comment]
![screenshot from 2016-08-26 15 05 34](https://cloud.githubusercontent.com/assets/2360494/18071624/c049320a-6e9a-11e6-9a63-81d806010f1d.png)

**Comment by whisere** [comment]
Mobile installation notes:

-----------------------------------------------------------------------
Problem:
Minds/minds/mobile/hooks/after_prepare/001_replace_config_variables.js:56
         throw "Missing config file: "+srcfile;
                                      ^
Missing config file: Minds/minds/mobile/config/config-dev.js
Error: Hook failed with error code 8: Minds/minds/mobile/hooks/after_prepare/001_replace_config_variables.js
Solved:
copy config-example.js to config-dev.js

----------------------------------------------------------------------
Problem:
Error: ENOENT, no such file or directory 'Minds/minds/mobile/platforms/android/res/raw/ringing.mp3'
Solved:
CopyMinds/minds/mobile/www/sounds/ringing-2.mp3 to Minds/minds/mobile/platforms/android/res/raw/ringing.mp3


----------------------------------------------------------------------------------------------------
Problem:
Error: Minds/minds/mobile/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_armv7DebugCompile'.
   > Could not find any version that matches com.android.support:support-v4:[21,22).
     Versions that do not match:
         24.1.1
         24.1.0
         24.0.0
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
         https://repo1.maven.org/maven2/com/android/support/support-v4/
         https://jcenter.bintray.com/com/android/support/support-v4/maven-metadata.xml
         https://download.01.org/crosswalk/releases/crosswalk/android/maven2/com/android/support/support-v4/maven-metadata.xml
         https://download.01.org/crosswalk/releases/crosswalk/android/maven2/com/android/support/support-v4/
     Required by:
         :android:unspecified > com.facebook.android:facebook-android-sdk:3.23.1


Solved:
http://stackoverflow.com/questions/33675491/could-not-resolve-all-dependencies-for-configuration-armv7debugcompile
----------------------------------------------------------------------------------------------------

Problem:
Execution failed for task ':mergeArmv7DebugResources'.
>Minds/minds/mobile/platforms/android/res/raw/ringing-2.mp3: Error: '-' is not a valid file-based resource name character: File-based resource names must contain only lowercase a-z, 0-9, or underscore
Solved:
Remove ringing-2.mp3
-----------------------------------------------------------------------------------------------------

Problem:

Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:591)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:546)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:528)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForArmv7Debug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 2
Solved:
remove android-support-v13.jar from platform/android/libs

-------------------------------------------------------------------------------------

**Comment by whisere** [comment]
So can anyone provide keyspaces data and structure? See the last item in the first post above and:

See engine/settings.php:
$CONFIG->cassandra = (object) [
'keyspace' => 'minds',
'servers' => [ '127.0.0.1' ],
'cql_servers' => [ '127.0.0.1:9042' ]
];

and engine/Spec/bootstrap.php:
$CONFIG->cassandra->keyspace = 'phpspec';
$CONFIG->cassandra->servers = array('127.0.0.1');
$CONFIG->cassandra->cql_servers = array('127.0.0.1:9042');

**Comment by markharding** [comment]
Thanks for the report. This ticket would probably be better as a blog on www.minds.com. 

@whisere yes, you can change the keyspace to whatever you want. 'phpspec' is a mock db.

**Comment by whisere** [comment]
Thanks, actually I haven't installed successfully yet. I found the keyspaces were not installed after running the bootstrap-ubuntu.sh, so I manually create them:
cqlsh> CREATE KEYSPACE minds WITH REPLICATION = { 'class' : 'NetworkTopologyStrategy', 'datacenter1' : 3 };
cqlsh> CREATE KEYSPACE phpspec WITH REPLICATION = { 'class' : 'NetworkTopologyStrategy', 'datacenter1' : 3 };

The front page is then showing but no response after clicking the links. So I guess the keyspaces need further setup with data, tables etc, hence the previous question about the keyspaces.

Now I try delete the settings.php file, delete minds keyspace and rerun  php /var/www/Minds/bin/cli.php install
it reports:
Installing Minds...
- Checking passed options: OK
- Building configuration file: OK
- Setting up data storage: Error connecting to 127.0.0.1: cassandra\InvalidRequestException:
Error connecting to 127.0.0.1: cassandra\InvalidRequestException:
PHP Notice:  Trying to get property of non-object in /var/www/Minds/engine/Core/Data/Cassandra/Client.php on line 19
PHP Notice:  Trying to get property of non-object in /var/www/Minds/engine/Core/Data/Cassandra/Client.php on line 20
OK
- Loading new configuration: OK
- Setting up site: OK
- Setting up administrative user: PHP Warning:  file_get_contents(): Filename cannot be empty in /var/www/Minds/engine/Entities/User.php on line 44
PHP Warning:  openssl_public_encrypt(): key parameter is not a valid public key in /var/www/Minds/engine/Helpers/OpenSSL.php on line 46
PHP Notice:  Undefined variable: recursive in /var/www/Minds/engine/classes/ElggUser.php on line 213
PHP Notice:  Trying to get property of non-object in /var/www/Minds/engine/classes/ElggEntity.php on line 851
PHP Warning:  strlen() expects parameter 1 to be string, object given in /var/www/Minds/engine/vendor/thobbs/phpcassa/lib/Thrift/StringFunc/Core.php on line 36
OK

cassandra is running ok, and keyspace minds is installed this time, but seems it is not right and the nginx log reports:
*21 FastCGI sent in stderr: "PHP message: PHP WARNING: 2016-09-08 01:11:25 (UTC): "Declaration of Minds\Core\Data\indexes::get($key_id, array $options = Array) should be compatible with Minds\Core\Data\Call::get($offset = '', $limit = 10)" in file /var/www/Minds/engine/Core/Data/indexes.php (line 0)" while reading response header from upstream, client: 130.56.24.27, server: _, request: "GET /api/v1/blog/featured?limit=4 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:",

**Comment by whisere** [comment]
Apart from the above, do we need to run setup-elastic.sh separately?  I tried running it and it reports:
Installed. Run with `./elasticsearch/bin/elasticsearch -d`
PHP Notice:  Undefined index: __elgg_session in /var/www/Minds/engine/Core/Security/XSRF.php on line 14
Exception #1473296178: Error: Class 'Minds\plugin\search\start' not found in /var/www/Minds/bin/misc/plugins.php:12
