### ISSUE TITLE
problem in installing 

### ISSUE THREAD

**Issue by nasservb** [Minds/minds#61]
we tried to install mind for all of the last week in multiple platform .
i have a problem in initializing with cli.php and in storing first data in cassandra steps .

i clone the project and installed all the requirements .
when i lunch the cli.php via terminal ,the program exit without any exceptions .
i search and debug the libraries and guess:

the phpcassa is deprecated library and when you call this library in
/minds/engin/core/data/ call.php -->keyspaceExists()
that exit application without error .
this function is called from cli.php .
and the phpcassa was not compatible with cassandra3(my installed version)
my project is running but I'm not able to login that because that is not connected to cassandra

**Comment by markharding** [comment]
Can you please post some error logs? We are not able to reproduce this error.

**Comment by nasservb** [comment]
i fixed that problem by reinstalling cpp_driver and libssl-dev1.0 (in ubuntu 16.04 by default libssl-dev1.1 is installed !) . 
but in fixing that error i saw some other error like : 
`- Setting up data storage (ignore errors, if any): Error connecting to 127.0.0.1: LegacyCassandra\InvalidRequestException`

this error raise when i try to install for first time by running /Minds/bin/cli.php
i try to fix that error for multiple time and run cli.php a lot . 
that's interesting to known in running after first time that error is hidden ! 
 
i consider the code expectation cycle and add debug log in several class and function to find reason of that problem . 
 when i call cli.php  ...  --cassandra-keyspace=minds17

**Comment by markharding** [comment]
Please try `vagrant destroy` and then do a pull again. Should work. 

Please post detailed error logs and re-open if you are still having issues.
