### ISSUE TITLE
Chapta element missing when trying to sign up

### ISSUE THREAD

**Issue by Aeller93** [Minds/minds#63]
Hello there, 
I just installed the dev version of Minds on my Mac. If I understand correctly, once the site loads on dev.minds.io, I should register, log in and then test the site around. However, when trying to sign up, the chapter element is missing. 
I checked the elements in the console and the re-chapta tag is there after the text fields, though it's empty. 
I have attached a few screenshots with the results in the dev tools and console for further reference. 
If anyone could help me find a solution I would greatly appreciate it, there are a few bugs I'm trying to fix. 
Thanks again

<img width="1262" alt="minds_bug_01" src="https://user-images.githubusercontent.com/28679966/30693589-1bee07dc-9e85-11e7-8ab7-db398e19a012.png">
<img width="449" alt="minds_bug_02" src="https://user-images.githubusercontent.com/28679966/30693590-1bfeb5c8-9e85-11e7-923b-083c367e422f.png">

**Comment by edgebal** [comment]
Hey!

1- Go to http://www.google.com/recaptcha and generate a site key and secret.
2- Open `engine/settings.php`, locate the `$CONFIG->set('google', ...` entry and add the following to the root array:
```
    'recaptcha' => [
        'site_key' => 'YOUR_SITE_KEY',
        'secret_key' => 'YOUR_SECRET_KEY'
    ]
```

Note: when developing, ensure you always have Dev Tools open with the cache disabled in the Network panel.

Cheers!

**Comment by markharding** [comment]
I think we're going to need a setting toggle in order to enabled/disable recaptcha, I suspect a lot of users won't want to use a third party service. @Aeller93, do you want to dig into this task?

**Comment by Aeller93** [comment]
@edgebal Thank you, worked like a charm. 
@markharding Sure, no problem. I think I can have it done by Monday.
