### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by Butonix** [Minds/minds#64]
Hello
Please write detailed installation and start-up instructions.
I think this will be useful not only for me, but for others
Thank you very much for your efforts.
Yours faithfully

**Comment by Aeller93** [comment]
@Butonix try https://github.com/Minds/minds/wiki/install

**Comment by ottman** [comment]
We will be consolidating the above link with https://minds.org/docs and some new fixes in the near future but you should be able to figure it out between those for now
