### ISSUE TITLE
Feature Request: Favorites/Watch Later

### ISSUE THREAD

**Issue by djh101** [Minds/minds#66]
A way to bookmark posts/videos to read/watch later would be very helpful; Watch Later is one of my favorite features of Youtube. A couple of other features that would be nice would be the ability to filter my feed, e.g. to show only videos, and to display these videos in a table/grid instead of having to scroll down one post at a time.

**Comment by Granitosaurus** [comment]
I feel that features like this are very redundant - your browser already has bookmarking function. 

It would be much more benefitial to use something domain agnostic for yourself and everyone involved really :)
Why have this feature implemented in every website when you can implement in a browser? At that's already done!

**Comment by djh101** [comment]
One issue with that solution is that it requires opening every post that you want to bookmark in its own separate page, as opposed to simply hitting the bookmark or watch later button/checkbox (I imagine this would be next to or under the arrow in the top right corner of each post) while scrolling down the home page.
