### ISSUE TITLE
Some minor enhancements & question about location of issues

### ISSUE THREAD

**Issue by OscarOrSomething** [Minds/minds#7]
First of all, Would like to ask if locations should be made on the repo of that particular module or on this module.

Other than this, Would just like to suggest some minor design tweaks, All my own opinion. Feel free to submit suggestions and I can make a PR with the changes if needed.

  - Make .newsfeed-grid and similar elements a little wider. ([Default (900px)](http://i.imgur.com/p9eeA4O.png), [Suggested (1000px)](http://i.imgur.com/38GdwMe.png)). Would also suggest that max-width shouldn't be in the element style, Is there something going on with the JS? Slow internet so I can't look at the repo properly right now, Sorry If I'm being dumb.
  - Make notifications a popup type thing. ([Like this](http://i.imgur.com/Z0YRZNd.jpg))

Great website, Thanks for making it.

**Comment by markharding** [comment]
Thanks for the ticket. If you could make a note on https://www.minds.com/groups/profile/100000000000000681/activity that would be great. Also please feel free to open a pull request and we'll take a look.
