### ISSUE TITLE
How to add other payment gateways services?

### ISSUE THREAD

**Issue by hdavy2002** [Minds/minds#72]
Please can you point me to the right direction.  I am looking to add paypal, stripe and Payumoney

**Comment by th3g3ntl3m2n** [comment]
Bitcoin and dash.

**Comment by Serkan-devel** [comment]
Bitcoin cash, LBRY Credits, STEEM

**Comment by Serkan-devel** [comment]
<BitconNEEEEEEEEEEEEEEEEEEEEEEEECCCCTTTT>

**Comment by Serkan-devel** [comment]
BitconnneeEEEEEEEEEEEEEEEeect
