### ISSUE TITLE
State of Docker

### ISSUE THREAD

**Issue by matanhershberg** [Minds/minds#78]
I was wondering what the state of dockerizing minds is.

Currently, running docker-compose only exposes port 80 for the nginx server, which just responds with a redirect.

I noticed that the README mentions that dockerization is a work in progress at the moment. I was hoping on either getting advice either on how to proceed, or if I might be better off just trying to dockerize from scratch (or at least just the nginx part).

Thanks

**Comment by ottman** [comment]
We have a major release coming late month, so stay tuned.

**Comment by matanhershberg** [comment]
Sounds good.

If I get something useful done before then I'll try to send a PR.

By the way, pretty awesome you got to meet Tucker, I like his stuff.

**Comment by markharding** [comment]
merging with #93
