### ISSUE TITLE
Can't use 'Object' as classname as it is reserved

### ISSUE THREAD

**Issue by gtcode** [Minds/minds#83]
OS: Ubuntu 16.04 (Mint 17.3)
PHP: PHP 7.2.3-1+ubuntu16.04.1+deb.sury.org

Error: 
```
$ php bin/cli.php install
PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /home/computer/projects/github/gtcode/minds/minds/engine/vendor/nette/nette/Nette/common/Object.php on line 53
```

**Comment by gtcode** [comment]
Works for php 7.0 - docs say "7" ambiguously, should say "7.0" explicitly.

**Comment by markharding** [comment]
Minds currently has some issues with PHP 7.2, I'd recommend PHP 7.1 for
now. Perhaps try our docker containers for optimum setup? (that's what we
run on production)

**Comment by gtcode** [comment]
Thanks Mark, will try, our other dev had some issues with docker

**Comment by gtcode** [comment]
@markharding Hi Mark, Quick questions about setting up Prod:  Docs say Ubuntu 14.04 with PHP 5.6.  Is this still the recommended path?  Will the docker setup work on 16.04/7.1?  Sorry just dealing with out of date docs and don't want to walk down experimental paths, better to ask you.  Thanks, Paul

**Comment by gtcode** [comment]
There are inconsistencies in the docs that cause lost time for developer.  The docs are not streamlined, missing steps, misleading.  Just needs some basic cleanup; since this is brand new to me I'm forced to fill in blanks and spend hours tinkering to get something running.

The dev and production environments should be consistent at least in terms of Ubuntu versions and package versions, assuming the same codebase is used in different environments.  It's reasonable to expect the developers to want to run instances of their production dependencies, as well, or at the least have them in some staging environment.

For instance if Cassandra is meant to be the single source of truth, it would be best to have Cassandra running on a local dev, staging and prod, etc., with a streamlined, singular path to set up the environment.  Docker is fine, but again should be streamlined/consistent.  And docs fixed to make it clear for newbie.  This will help project adoption.  Too many hurdles currently for someone who is curious, spending time figuring these things out that good docs would solve.

Sorry for rant just my 2 ct

**Comment by markharding** [comment]
PHP 7.1 is the supported build (PHP7.2 drops some things we need to refactor first). Merging with #93 as this should make it all clear
