### ISSUE TITLE
cli.php: [ERROR] Email private key path was not provided

### ISSUE THREAD

**Issue by gtcode** [Minds/minds#84]
Likely a documentation issue?

OS: Ubuntu 16.04 (Mint 17.3)
PHP: 7.0-cli

Command: `$ php bin/cli.php  install --domain=dev.minds.io --username=admin --password=password --email=minds-superadmin@test.com --no-https`

Output:
```
- Checking passed options: 
cli.php: [ERROR] Email private key path was not provided
```

**Comment by gtcode** [comment]
From the README.md:
` --private-key=/.dev/minds.pem --public-key=/.dev/minds.pub`

**Comment by gtcode** [comment]
I settled on these steps to get past it:
1) `php bin/cli.php install keys`
2) `php bin/cli.php install --domain=dev.minds.io --username=admin --password=password --email=minds-superadmin@test.com --email-private-key=/.dev/minds.pem --email-public-key=/.dev/minds.pub --private-key=/.dev/minds.pem --public-key=/.dev/minds.pub --phone-number-private-key=/.dev/minds.pem --phone-number-public-key=/.dev/minds.pub --no-https`

This now introduces:

```- Checking passed options: OK
- Building configuration file: OK
- Loading new configuration: OK
- Setting up data storage (ignore errors, if any): Error connecting to 127.0.0.1: Thrift\Exception\TException: TSocket: Could not connect to 127.0.0.1:9160 (Connection refused [111])
Error connecting to 127.0.0.1: Thrift\Exception\TException: TSocket: Could not connect to 127.0.0.1:9160 (Connection refused [111])

cli.php: [EXCEPTION:Thrift\Exception\TException] TSocket: Could not connect to 127.0.0.1:9160 (Connection refused [111])
```

I've performed all of the prelim steps but need to backtrack I suppose.

**Comment by gtcode** [comment]
This could very well be docs being out of date, and/or something on my machine.. but at the least, docs out of date.

**Comment by gtcode** [comment]
I was able to backtrack and redo composer install and believe the base `cli.php install` is done.  IDK if I did something wrong originally but it seemed to need the changes related to the priv/pub keys.

**Comment by markharding** [comment]
Merging with #93
