### ISSUE TITLE
Project documentation is very out of date, status of code unknown

### ISSUE THREAD

**Issue by gtcode** [Minds/minds#85]
I'm having a hard time getting an installation going.  Next up is docker but it's not well-documented, either.

If the basic procedure to get an instance going, either on an VPS, AWS, Azure, or Bare Metal internet server, or locally, is not straightforward on the README.md, then it's difficult to evaluate the system.  As of now I am eight hours into going through various procedures cobbled together from the out-of-date docs, discovering problems along the way but hopeful that I simply have not tried the "magic" version that is known to work, whether vagrant/vb (which I don't have installed) or docker (which, again, isn't documented but I will try now).

Many little bugs here and there have been encountered, and things like the hard coded production easy install script for Ubuntu 14.04 with PHP 7.0 and unclear requirements has issues, has a hard coded URL and missing parameters.

What the project really needs is for someone to deprecate or at least hide any non-working procedures, clean up the ones that do work on a known server environment (e.g. Ubuntu 14.04 LTS barebones, known to work on: AWS with this AMI, etc), or at least have the docker procedure cleaned up, and everything else hidden.

Without this, anyone evaluating the project is going to give up and move on.  Someone has to take ownership of these basic issues before the project will be taken seriously.  Sorry for the candid post -- I could simply have "chosen" wrong but the README clearly says docker is experimental.  I'll keep trying to see if there's a straightforward way to get an install going, but already this involves hand-rolling installation docs to accommodate the out-of-date docs, with little fixes here and there to the code/scripts/etc along the way.

**Comment by gtcode** [comment]
I'd suggest a very explicit step-by-step idiot proof install. Such as:
1) Install AMI xyz on EC2 (Ubuntu 14.04 LTS vanilla whatever)
2) SSH in using default user
3) Create this user
4) Add this SSH key like so
5) sudo apt-get install these exact dependencies
6) run this script, install this docker command precisely like so: 'foo bar baz'

Should be completely idiot-proof, for, you know, idiots :-D like me

**Comment by gtcode** [comment]
Code does look nice, which had me excited, especially given that it's a proprietary layout.. someone seemed to have strong dev skills creating this thing so to me it is/was worth the stretch working around these initial issues.

Ok, for instance:
https://www.minds.org/docs/install/requirements.html

This is extremely ambiguous.  Just mentions pre-requisites without any specifics.  Then goes on to some helper ubuntu 14.04 script that mostly works but does have hard coded stuff like a domain name. Why would a production set up script have a hard coded domain name?

It's also missing those required `cli.php install` email and so on parameters that I referenced one or two tickets back.  More bugs.

And little bugs like re-running in and trying to create a dir that already exists, just some very basic code smells that should be cleaned up for sure, so a new developer has a solid impression about evaluating the project.

The docs could almost be thrown out, or put aside and have a new set of docs that are extremely step-by-step with explicit references to known working distros... or even if possible an already created AMI which is a bit optimistic but nice to have if possible

Our other dev did try vagrant and docker approaches which didnt work -- these should almost certainly work smoothly and should be explicitly described as isolated approaches for installation, not kind of rolled in with the rest of the procedures.

Being that the code itself does look pretty nice, and since the project does involve some really cool technologies that an up-and-coming dev would love to use, such as Cassandra, Neo4j and so on, IMHO it would be *very worthwhile* for someone to take ownership of these project onboarding issues; someone who is experienced with writing or developing procedures that are meant to be extremely beginner/user-friendly.  Given all of the work that went into the project over the years, depth of features and what seems to be a quite pleasant layout of actual php source code for the engine (which I cannot evaluate until I can install the system), it should be worthwhile to do this.  

I'd love to but I have to actually get the system working first to do so, and this takes time and energy!  My first goal was to try to get *anything* working using *any* method described in the docs, but since there are so many and since each one takes time, I've wasted time trying to do so unsuccessfully thus far.   I concede someone else may have better "luck" getting the project going quickly in dev or on a web server, but it should not require expertise to do so.

During one attempt, I did start going through the website docs procedure using Ubuntu 16.04 and PHP 7.1 which is likely a good idea for "development" (development of MINDS, not for someone developing their system which would want a homogeneous server configuration from local dev, to staging, to production, as much as possible) anyway.  So my thought is that someone could take the quick-install script in bin and adapt it for Ubuntu 16.04 LTS.  Much of the dependencies are way more user friendly.

Having said that, it seems that docker is perhaps the path that is preferred but if that's the case it should be finalized/stabilized, with explicit hiding and/or deprecation of any other procedures.  Most important is to give a new user evaluating Minds an extremely clear, concise, explicit, and fool-proof way to install the system on any given environment, regardless of how that is achieved.

Hope this helps. :-D

**Comment by gtcode** [comment]
Some other info that would be helpful: Details on minimum and reasonable requirements for CPU, Memory, Disk on, for instance AWS and/or Azure.

**Comment by gtcode** [comment]
@markharding - I have no idea if any of this is right or will work, but since we are desperate to get this done ASAP, I'm posting a progress version now.  It's not done yet.  Can you look it over?  I'll keep updating it:

# Minds Production Server Setup Procedure:

### Provision Server on Azure

Get the id_rsa.pub from your local machine's terminal user account, and copy to clipboard or set aside for next step

Provision Azure Linux 14.04 with username that matches your local machine's terminal username (makes it easier)
*Use passwordless auth, match username to local username, use the id_rsa.pub from previous step.
*2 cores, 16 GB, 128GB

### Bootstrap machine via ssh

On local machine, edit /etc/hosts and add entry:
```
(ip_address_from_azure) (chosen_server_name_to_use_from_local)
```

Log in via ssh (You should be able to omit (user)@ if you used same username as local username when provisioning server:
```
ssh (user)@(chosen_server_name_from_local)
```

Enable ufw for 80, 443, 22:
```
sudo -i
ufw allow ssh
ufw allow http
ufw allow https
ufw enable
ufw status
(confirm 80,443,22 for IPv4 and IPv6 [6 lines total])
```

Edit bash history length for root and your non-root user:
`vim ~/.bashrc`
` (change 1000 to 1000000 and change 2000 to 2000000)`

### Install base packages

Install git:
```
sudo apt-get install nginx git
```

Set up code, as your non-root user:
REF: https://www.minds.org/docs/install/download.html:
```
cd /var/www
git clone https://github.com/minds/minds.git Minds
cd Minds
chmod +x init.sh
./init.sh
```

Install php5.6 and nginx:
```
sudo add-apt-repository ppa:ondrej/php
sudo apt-get install php5.6-fpm
sudo apt-get install nginx
```

Create directory and initial perms
```
sudo mkdir /var/www
sudo chown www-data:www-data /var/www
```

Set user permissions for safe access to /var/www as non-root user:
REF: https://askubuntu.com/questions/46331/how-to-avoid-using-sudo-when-working-in-var-www (Solution 1)
```
sudo gpasswd -a "$USER" www-data
sudo chown -R "$USER":www-data /var/www
find /var/www -type f -exec chmod 0660 {} \;
sudo find /var/www -type d -exec chmod 2770 {} \;
```

Install more php5.6 modules:
```
sudo apt-get install php5.6-xml php5.6-mongodb php5.6-bcmath
```

Install composer:
###### REF 1: download step/verify: https://getcomposer.org/download/
###### REF 2: actual install step, install globally: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-composer-on-ubuntu-16-04
```
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer
php -r "unlink('composer-setup.php');"
```

Install node 9 and related
REF: https://nodejs.org/en/download/package-manager/
```
curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo apt-get install -y build-essential
```

Install gulp, typings, typescript:
REF: https://www.minds.org/docs/install/requirements.html
```
sudo npm install -g gulp
sudo npm install -g typings
sudo npm install -g typescript
```

Preparation steps: 
REF: https://www.minds.org/docs/install/preparation.html#
```
cd /var/www/Minds
cd front
npm install
npm run build  ## if it fails try re-running
cd ../engine
composer install
```

Fix bootstrap-ubuntu.sh script per this commit until it's merged:
```
https://
```

Provision production:
REF: https://www.minds.org/docs/install/vagrant.html#production:
```
cd var/www/Minds
chmod +x bin/bootstrap-ubuntu.sh
sudo ./bin/bootstrap-ubuntu.sh
```

### DOCKER

Set up docker and docker-compose using latest versions from Docker site:
REF: https://docs.docker.com/install/linux/docker-ce/ubuntu/#prerequisites
```
sudo apt-get update
sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
```

Install Docker CE (TODO: update this to specify stable version for production):
REF: https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-docker-ce
```
sudo apt-get update
sudo apt-get install docker-ce
```

Post-install (to use docker as regular user):
REF: https://docs.docker.com/install/linux/linux-postinstall/
```
sudo groupadd docker
sudo usermod -aG docker $USER
```

Log out and log back in, then:
```
docker run hello-world
```
(Should not show any errors)

Install Docker Compose:
REF: https://docs.docker.com/compose/install/
```
sudo curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
```

Test docker compose:
```
docker-compose --version
```

**Comment by kyphosis** [comment]
@gtcode I'm stuck at doing composer install, any handy tips?
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phpdocumentor/reflection-docblock 4.2.0 -> satisfiable by phpdocumentor/reflection-docblock[4.2.0].
    - phpdocumentor/reflection-docblock 4.2.0 requires php ^7.0 -> your PHP version (5.6.35) does not satisfy that requirement.
  Problem 2
    - Installation request for sebastian/comparator 2.0.0 -> satisfiable by sebastian/comparator[2.0.0].
    - sebastian/comparator 2.0.0 requires php ^7.0 -> your PHP version (5.6.35) does not satisfy that requirement.
  Problem 3
    - Installation request for sebastian/exporter 3.1.0 -> satisfiable by sebastian/exporter[3.1.0].
    - sebastian/exporter 3.1.0 requires php ^7.0 -> your PHP version (5.6.35) does not satisfy that requirement.
  Problem 4
    - Installation request for sebastian/recursion-context 3.0.0 -> satisfiable by sebastian/recursion-context[3.0.0].
    - sebastian/recursion-context 3.0.0 requires php ^7.0 -> your PHP version (5.6.35) does not satisfy that requirement.
  Problem 5
    - sebastian/exporter 3.1.0 requires php ^7.0 -> your PHP version (5.6.35) does not satisfy that requirement.
    - phpspec/phpspec 2.5.8 requires sebastian/exporter ~1.0|~2.0|^3.0 -> satisfiable by sebastian/exporter[3.1.0].
    - Installation request for phpspec/phpspec 2.5.8 -> satisfiable by phpspec/phpspec[2.5.8].
```

**Comment by markharding** [comment]
I'm going to close this so we condense all installation discussion to #93. We're going to be updating the docs this week.

**Comment by markharding** [comment]
@kyphosis You need PHP 7.. new docs later this week will help.
