### ISSUE TITLE
docker-compose up results in Fatal error: require_once()

### ISSUE THREAD

**Issue by noiseunit** [Minds/minds#88]
Looks like there are some path errors on `docker-compose up`

runners_1 | [05-Apr-2018 00:19:15 UTC] PHP Fatal error: require_once(): Failed opening required '/var/www/Minds/engine/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/Minds/engine/cli.php on line 9
runners_1 | 2018-04-05 00:19:15,266 DEBG 'minds-feeds_01' stdout output:
runners_1 | [05-Apr-2018 00:19:15 UTC] PHP Fatal error: require_once(): Failed opening required '/var/www/Minds/engine/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/Minds/engine/cli.php on line 9
runners_1 | 
runners_1 | 2018-04-05 00:19:15,266 DEBG 'minds-feeds_01' stdout output:
runners_1 | [05-Apr-2018 00:19:15 UTC] PHP Fatal error: require_once(): Failed opening required '/var/www/Minds/engine/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/Minds/engine/cli.php on line 9
runners_1 | 
runners_1 | 
runners_1 | Fatal error: require_once(): Failed opening required '/var/www/Minds/engine/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/Minds/engine/cli.php on line 9
runners_1 | 2018-04-05 00:19:15,266 DEBG 'minds-feeds_01' stdout output:
runners_1 | 
runners_1 | Fatal error: require_once(): Failed opening required '/var/www/Minds/engine/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/Minds/engine/cli.php on line 9
runners_1 | 
runners_1 | 2018-04-05 00:19:15,266 DEBG 'minds-feeds_01' stdout output:
runners_1 | 
runners_1 | Fatal error: require_once(): Failed opening required '/var/www/Minds/engine/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/Minds/engine/cli.php on line 9
runners_1 |

**Comment by markharding** [comment]
Can you check your engine directory is populated?

**Comment by noiseunit** [comment]
Yep (screenshot). It sort of starts up but the fatal errors are unexpected I'm sure.

$ docker ps
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                                NAMES
14b26439be0a        minds_nginx                "nginx -g 'daemon of…"   10 hours ago        Up 35 seconds       0.0.0.0:8080->80/tcp                 minds_nginx_1
0f7bc23b6b5a        minds_php-fpm              "docker-php-entrypoi…"   10 hours ago        Up 36 seconds       9000/tcp                             minds_php-fpm_1
314f06553c69        minds_runners              "supervisord --nodae…"   10 hours ago        Up 37 seconds       9000/tcp                             minds_runners_1
655bec8ec949        redis:4.0-alpine           "docker-entrypoint.s…"   10 hours ago        Up 38 seconds       6379/tcp                             minds_redis_1
6e4e2907fd2e        elasticsearch:5.6-alpine   "/docker-entrypoint.…"   10 hours ago        Up 37 seconds       9200/tcp, 9300/tcp                   minds_elasticsearch_1
54c3be61bb6f        mongo:3.4                  "docker-entrypoint.s…"   10 hours ago        Up 37 seconds       27017/tcp                            minds_mongo_1
52a55bfd7f60        rabbitmq:3.6-alpine        "docker-entrypoint.s…"   10 hours ago        Up 37 seconds       4369/tcp, 5671-5672/tcp, 25672/tcp   minds_rabbitmq_1

<img width="616" alt="screen shot 2018-04-05 at 6 51 01 pm" src="https://user-images.githubusercontent.com/38076740/38397281-79737e24-3902-11e8-94d5-2d5b09a42c6b.png">

**Comment by markharding** [comment]
Did you run `composer install`?

**Comment by noiseunit** [comment]
I am unable to get Composer installed on my system, so unfortunately I am unable to help with this issue further other than if I ever get some free time I will put everything that you have Composer doing outside the docker container and put it inside the docker container.

**Comment by markharding** [comment]
Docker doesn't run the install of the vendors at this time. Checkout https://getcomposer.org/
