### ISSUE TITLE
(feat): Implement ActivityPub

### ISSUE THREAD

**Issue by chrisgraham** [Minds/minds#90]
You should consider implementing the ActivityPub standard. This is a W3C standard, and if all the alternative social networks implement it, you'll be collectively much stronger.

**Comment by markharding** [comment]
Thanks Chris. We are looking for community help for this task. Are you interested?

**Comment by ottman** [comment]
We are deep in dev stabilizing the platform as you can see from commit history and will be focusing more on the open source community this year. Patience is appreciated. We just spent a ton of time open sourcing the sockets and webtorrent today. Crypto is coming very soon. Please stay on top of us

**Comment by chrisgraham** [comment]
I don't have spare time to volunteer on coding projects, sorry. I have my own huge Open Source project to maintain, then what little time I have left has to go on paid work.

**Comment by Granitosaurus** [comment]
I feel that FLOSS community is a bit lacking in php devs. 

However Hubzilla has activitypub implementation in php so there's a really great example to follow :)

**Comment by Serkan-devel** [comment]
How was it decided to use php at all?

**Comment by Granitosaurus** [comment]
@Serkan-devel I don't know but I feel that php is a really difficult language for minor contributions unless you're a professional php dev yourself.  
I can understand and have minor contributions to go, ruby, nim and whatnot with basic understanding as a professional Python dev but I've spent half a day trying to figure out how newsfeed REST engine on minds works and still I couldn't really figure out how to make a PR out of it :laughing:

**Comment by m4sk1n** [comment]
I think Minds/engine/#28 deserves more attention
