### ISSUE TITLE
(chore): Documentation / Installation

### ISSUE THREAD

**Issue by ghost** [Minds/minds#93]
Could you update the documentation for installing minds? The documentation seems to be very outdated.

**Comment by markharding** [comment]
Yes, we need help from the community here. Any takers?

**Comment by gtcode** [comment]
Already took a stab at this, got zero response from anyone:

https://github.com/Minds/minds/issues/85

**Comment by markharding** [comment]
@gtcode perhaps you could open a pull request so we can review it?

**Comment by gtcode** [comment]
@markharding No, because I wasn't able to complete it.  It really needs someone who knows the project to review my progress based on that linked ticket (or create their own version).  I was attempting to get ANYTHING going using the docker method and it didn't work out.

**Comment by markharding** [comment]
Whilst we work on improving the installation docs, the following build files might be helpful. This is what our CI system uses everytime we push any changes.

Engine - https://github.com/Minds/engine/blob/master/.drone.yml#L3
Front - https://github.com/Minds/front/blob/master/.drone.yml

**Comment by Serkan-devel** [comment]
@markharding why are the drone CI web interface not public?

**Comment by markharding** [comment]
We will eventually, but right now it would just be repeating what is
happening internally. We'd also need to make some changes so it skips the
deploy stages.

**Comment by DarkBlaez** [comment]
What is the target date for getting the documentation and install up to date? I have seen this before with Joyent where they close issues on git without resolution. Is the git code base operational? Thus far no-one has been able to bring this up without issues (VM, baremetal, nothing). So what is the target date for insuring the code can be installed in a clean environment and operational? There are many who would like to contribute but this seems like a way to keep others from doing so. How about one of the core devs take half-day and get this resolved? I contend that the code in git is non-operational and would like to be proven wrong.

-DB

**Comment by ottman** [comment]
It's on the next sprint stay tuned and patience is appreciated

**Comment by DarkBlaez** [comment]
Bill what is the target date for the start of the next sprint or completion there of? Most sprints are 2 to 3 weeks, so curious as to the target for resolving this significant issue impeding others from contributing

-DB

**Comment by markharding** [comment]
I've updated the README [here](https://github.com/Minds/minds/commit/be254a793af4b3e59174e8befcfa62cb36ba8ae8) https://github.com/Minds/minds/commit/be254a793af4b3e59174e8befcfa62cb36ba8ae8 and also the docs over at [minds.org/docs](https://minds.org/docs).

Before running these instructions please make sure you're doing it from a fresh state (ie. ensure settings.php is deleted). These containers are what we run on production and the steps are what I have also used locally on Mac OSX. If you're still having issues then I'd be happy to hop on a call so we can isolate them. 

Also, we still require community help with the docs. If anybody would like to contribute them please let us know.

**Comment by markharding** [comment]
For quick reference:

## Development Installation

1. Run `sh init.sh` in order to install the front and engine repositories
2. Run `docker-compose up -d nginx`
3. Run `docker-compose exec cassandra nodetool enablethrift`
4. Run `docker-compose up installer` (one time only.. initial username: minds / password: password)
5. Run `docker-compose up front-build` 
6. Navigate to `http://localhost:8080`

### Troubleshooting

- Minds is already installed
  - Ensure engine/settings.php does not exist and re-run `docker-compose up installer`

- Cassandra will not boot
  - Ensure thrift is enabled
  - Cassandra requires at least 4GB of memory to operate. You can start Cassandra manually by running `docker-compose up cassandra`

**Comment by Serkan-devel** [comment]
@markharding wouldn't be easier to run `git clone --recusive` instead of an init.sh file?

**Comment by markharding** [comment]
`git clone --recusive` is for the internal repos (they are the same but we have development branches and its linked to the internal CI etc).

**Comment by gem2578** [comment]
https://github.com/Minds/minds/pull/101

**Comment by Serkan-devel** [comment]
@markharding doesn't it make it seem less open source and less convenient for contributors this way or am I missing something?

**Comment by markharding** [comment]
Not at all. We have internal development branches and we also have internal
CI tools that have no reason to be public (at least for now). What runs on
Minds.com is 100% opensource, github purely acts as a mirror of our code.

**Comment by Serkan-devel** [comment]
So does the same code, which is open, run on minds servers?

**Comment by Serkan-devel** [comment]
Can I use the regular open repositories and have the same outcome when running it (not considering hardware here)?

**Comment by markharding** [comment]
Yes
