### ISSUE TITLE
(feat): ability to hide posts.

### ISSUE THREAD

**Issue by Granitosaurus** [Minds/minds#94]
It would be nice if you could hide posts permanently from your feeds.

### Reasoning

It really sucks to see the same posts over and over again. Especially from channels you like so you cannot block them and if those posts are broad enough they even appear on multiple feeds - which really sucks.  

Hiding posts will also help discoverability and increase meaningful engagement.

**Comment by markharding** [comment]
Please checkout https://www.minds.com/groups/profile/100000000000000681 for community requests.

**Comment by Granitosaurus** [comment]
Hey @markharding 
Why would open source projects feature suggestions go to anywhere but the issue tracker? Isn't that's the whole point of the issue tracker? 
It's seems a bit backwards to discuss this on 2nd party system. 

To add to that the minds.com group is not a place where you can propose code changes, share snipets and attach PR. So really I'm just confused by this if anything.

**Comment by Serkan-devel** [comment]
It's even harder to search for issues if they have been proposed long ago. It's like using Facebook as an issue-tracker

**Comment by Serkan-devel** [comment]
Is there a way to natively link github code on minds, or make the interaction for development more seamless?

**Comment by markharding** [comment]
We need to keep the github environment purely for technical issues and separate from consumer end requests or else it will become out of hand. (Theres an unlimited amount of features).

That being said, if you have a pull request with a solution, then please do open a PR request and we'll go from there!

**Comment by Serkan-devel** [comment]
Post about this pr https://github.com/Minds/minds/pull/77 has been rejected on the Minds open source group (at least it hasn't been approved, but others were). I still didn't get any answers about it for months on minds.

**Comment by ottman** [comment]
We are going to be coming out with a better process for feature requests and prioritization than the support group in the future but you have to understand we have thousands of requests and GitHub isn't the right place. We are logging everything mentioned.

**Comment by Serkan-devel** [comment]
Maybe a custom issue board on minds, which one can easily look into the first issue for example
