### ISSUE TITLE
OSX - Error when following instructions

### ISSUE THREAD

**Issue by DarkBlaez** [Minds/minds#95]
Any thoughts on this error. Followed the Wikin install instructions, have all dependencies installed.

vagrant up --- results in this after it runs...  (machine is OSX mac with 16G ram and plenty of resources)

    default:  EPERM: operation not permitted, chown '/var/www/Minds/engine/vendor/minds/mw3/node_modules/.staging/number-to-bn-18a4835d/src/tests'
    default: npm WARN tar EPERM: operation not permitted, fchown
    default: npm WARN rollback Rolling back rlp@2.0.0 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/var/www/Minds/engine/vendor/minds/mw3/node_modules/rlp/.nfs00000002006f267f00000002'
    default: npm WARN rollback Rolling back ethjs-signer@0.1.1 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/var/www/Minds/engine/vendor/minds/mw3/node_modules/ethjs-signer/.nfs00000002006f268000000001'
    default: npm WARN mw3@0.0.1 No description
    default: npm ERR! path /var/www/Minds/engine/vendor/minds/mw3/node_modules/rlp/bin/rlp
    default: npm ERR! code ENOENT
    default: npm ERR! errno -2
    default: npm ERR! syscall chmod
    default: npm ERR!
    default:  enoent
    default:  ENOENT: no such file or directory, chmod '/var/www/Minds/engine/vendor/minds/mw3/node_modules/rlp/bin/rlp'
    default: npm ERR! enoent This is related to npm not being able to find a file.
    default: npm ERR! enoent 
    default: 
    default: npm 
    default: ERR! A complete log of this run can be found in:
    default: npm 
    default: ERR!     /root/.npm/_logs/2018-04-24T16_08_02_885Z-debug.log
    default: Do not run Composer as root/super user! See https://getcomposer.org/root for details
    default: Loading composer repositories with package information
    default: Installing dependencies (including require-dev) from lock file
    default: Nothing to install or update
    default: Package facebook/php-sdk-v4 is abandoned, you should avoid using it. Use facebook/graph-sdk instead.
    default: Package graphaware/neo4j-response-formatter is abandoned, you should avoid using it. No replacement was suggested.
    default: Package neoxygen/neoclient is abandoned, you should avoid using it. Use graphaware/neo4j-php-client instead.
    default: Package videlalvaro/php-amqplib is abandoned, you should avoid using it. Use php-amqplib/php-amqplib instead.
    default: Generating autoload files
    default: /home/vagrant
    default: Installing Minds…
    default: PHP Warning:  mkdir(): File exists in /var/www/Minds/bin/regenerateDevKeys.php on line 13
    default: - Checking passed options: 
    default: 
    default: cli.php: [ERROR] Email private key path was not provided
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

Has anyone done a fresh install? Usually waht I have found even as a developer that once we do the initial install on our development boxes, everything working, we rarely go back and do a fresh install to be sure we are not using depricated libraries and so forth.

Again, this was by the steps referenced in the Wiki

-DB

**Comment by markharding** [comment]
I'm going to close this so we condense all installation discussion to #93. We're going to be updating the docs this week.

**Comment by therobyouknow** [comment]
also need to do the symlink similarly for any output: css js svg img etc - as same PERM error would be encountered. I found this to work.
