### ISSUE TITLE
Documentation / api endpoints.

### ISSUE THREAD

**Issue by Granitosaurus** [Minds/minds#97]
Hey,
I'd like to contribute some documentation to api endpoints. 
I'd like to know whether we have established standard for that and what's documentation format?

**Comment by Granitosaurus** [comment]
@Serkan-devel yeah I've looked into that thread. It doesn't really answer my question regarding what format we're using for docs as I don't see any docs in the repo. 
I could just dump a bunch of markdown docs as a PR but I feel that there are better formats than markdown for documentation (like rst). So I'd like to know what the preferred approach here. :man_shrugging:

**Comment by ottman** [comment]
We already have something started and will get back to you soon. So much
going on and your engagement/patience is appreciated.

**Comment by markharding** [comment]
Do you mean the rest apis or the internal code apis?

**Comment by Serkan-devel** [comment]
Probably the APIs which one can access as a user

**Comment by Granitosaurus** [comment]
@markharding I meant REST apis, for people who'd like to either to contribute to fron-end or 3rd party tools like GUI wrappers and such.
