### ISSUE TITLE
(bug): cassandra_1 | chown: cannot access '/var/log/cassandra': No such file or directory

### ISSUE THREAD

**Issue by kyphosis** [Minds/minds#99]
Thanks for updating the docs, spinned up with DO droplet to check if I can build my instance of minds.

When doing `# docker-compose up -d nginx
`
It returns me error `ERROR: Cannot locate specified Dockerfile: ./containers/nginx/Dockerfile.dev
`
Could i get help with this? Double checked and the Dockerfile.dev exists in specified directory.

Tagging @markharding since you replied quite fast last time I posted about documentation issue.

**Comment by markharding** [comment]
Fixed in https://github.com/Minds/minds/commit/7b2ba46ec1281aaadaa11a9fdb9fafce8c69aa69

For the casandra part can you try creating the `cassandra` folder in the root of the minds directory?

**Comment by markharding** [comment]
Also try creating the `log` folder in the root of the minds directory?

**Comment by kyphosis** [comment]
Still same issue :(

**Comment by markharding** [comment]
We can hop on a quick call if you want? https://meet.jit.si//721624876363225

**Comment by kyphosis** [comment]
Sure, hopping on.

**Comment by DarkBlaez** [comment]
I can confirm this is an issue. I have encountered it as follows:

docker-compose exec cassandra nodetool enablethrift
ERROR: No container found for cassandra_1

I'm pretty sure the follow up steps will yield the results above. Is there any resolution on this since it was first posted?

-DB

**Comment by DarkBlaez** [comment]
This is what the cassandra container is tossing so it does not run. Looks like something local on permissions or the volume mapping

cassandra_1      | chown: cannot access '/var/log/cassandra': No such file or directory
minds_cassandra_1 exited with code 1

**Comment by kyphosis** [comment]
Hey @DarkBlaez you can copy my docker-compose.yml and it will work.
`# Using v2.2 because v3+ is meant for swarm operations
version: "2.2"

services:
  cassandra:
    image: cassandra:3.11.1
    environment:
      - CASSANDRA_START_RPC=true
    networks:
      - app
   # mem_limit: 4048MB
    #volumes:
      #- "./cassandra:/var/lib/cassandra:cached"
      #- "./logs:/var/log"

  mongo:
    image: mongo:3.4
    networks:
      - app

  elasticsearch:
    image: elasticsearch:5.6-alpine
    mem_limit: 512MB # keep an eye
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    networks:
      - app

  redis:
    image: redis:4.0-alpine
    mem_limit: 100MB # keep an eye
    networks:
      - app

  rabbitmq:
    image: rabbitmq:3.6-alpine
    networks:
      - app

  php-fpm:
    build:
      context: ./engine
      dockerfile: ./containers/php-fpm/Dockerfile
    mem_limit: 2048MB
    depends_on:
      - cassandra
      #- mongo
      #- elasticsearch
      #- rabbitmq
      - redis
    networks:
      - app
    volumes:
      ## The following is for development environments only. Comment out on production. ##
      - "./front/:/var/www/Minds/front:cached"
      - "./plugins/:/var/www/Minds/plugins:cached"
      - "./languages/:/var/www/Minds/languages:cached"
      ## The following is for development environments only. Comment out on production. ##
      - "./engine/:/var/www/Minds/engine:cached"

  runners:
    build:
      context: ./engine
      dockerfile: ./containers/php-runners/Dockerfile
    depends_on:
      - cassandra
    #  - mongo
    #  - elasticsearch
    #  - rabbitmq
      - redis
    networks:
      - app
    volumes:
      - "./front/:/var/www/Minds/front:cached"
      - "./plugins/:/var/www/Minds/plugins"
      - "./languages/:/var/www/Minds/languages"
      - "./engine/:/var/www/Minds/engine"

  nginx:
    build:
      context: ./containers/nginx
      dockerfile: ./Dockerfile.dev
    mem_limit: 512MB
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
    networks:
      - app
    volumes:
      ## The following is for development environments only. Comment out on production. ##
      - "./front/:/var/www/Minds/front:cached"

  installer:
    build:
      context: ./engine
      dockerfile: ./containers/installer/Dockerfile
    networks:
      - app
    volumes:
      - "./engine/:/var/www/Minds/engine"
      - "./front/:/var/www/Minds/front"

  front-build:
    image: markharding/minds-front-base
    networks:
      - app
    entrypoint: 
      - sh
      - -c
      - "cd /var/www/Minds/front && npm install && npm rebuild node-sass && npm run build-dev"
    volumes:
      - "./front/:/var/www/Minds/front"

networks:
  app:
    driver: "bridge"`

**Comment by kyphosis** [comment]
Or alternatively just # out the following lines 
   # mem_limit: 4048MB
    #volumes:
      #- "./cassandra:/var/lib/cassandra:cached"
      #- "./logs:/var/log"

**Comment by DarkBlaez** [comment]
Thanks anf will do

**Comment by kyphosis** [comment]
If you're not on local you might need to do some modifications, in order to run this correctly.
Closing this as seems to be fixed for @DarkBlaez

**Comment by kyphosis** [comment]
Please follow the updated documentation.

**Comment by DarkBlaez** [comment]
I did. Without stating my background, my involvment with Docker, or such, suffice it to say this is not my first rodeo. However, I will put this on several new clean VMs and follow the steps again, documenting as I go. I will then fork this repo and pull my team in to streamline and fix the outstanding kludge of steps

-DB

**Comment by kyphosis** [comment]
What are your computer specs?..
I followed updated documentation and it worked.

**Comment by Rose901** [comment]
Hi I am having the same problem when following the step-by-step instructions:

```
docker-compose exec cassandra nodetool enablethrift
ERROR: No container found for cassandra_1
```

**Comment by boreys** [comment]
the same issue with cassandra
cassandra_1      | chown: cannot access '/var/log/cassandra': No such file or directory

**Comment by songproducer** [comment]
Any update on this? I'm having the same issue

**Comment by achabanov** [comment]
Following up on this.

running:
sudo docker-compose exec cassandra nodetool enablethrift
results in:
ERROR: No container found for cassandra_1

Is there a solution you guys can share @songproducer @boreys  @DarkBlaez @markharding ? Thank you.

**Comment by ysthedood** [comment]
I tried deleting commenting out the following lines:
` mem_limit: 4048MB
    volumes:
      - "./cassandra:/var/lib/cassandra:cached"
      - "./logs:/var/log"`
as stated in @kyphosis answer. However, after running `sudo docker-compose up cassandra`, I get `minds_cassandra_1 exited with code 137`

**Comment by Zyther** [comment]
Hey guys, 

After pounding my head for a while, I found the solution:
Relative to the `minds` repo, create a `cassandra` directory inside `logs`

Cheers!
